"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('email', name=op.f('uq_admins_email')),
    schema='hirely'
    )
    op.create_table('advertisers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advertisers')),
    sa.UniqueConstraint('name', name=op.f('uq_advertisers_name')),
    schema='hirely'
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('market', sa.String(length=40), server_default='uz', nullable=False),
    sa.Column('platform', sa.String(length=40), server_default='telegram', nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('code', name=op.f('uq_channels_code')),
    sa.UniqueConstraint('prefix', name=op.f('uq_channels_prefix')),
    schema='hirely'
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('internal_ref', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('telegram', sa.String(length=40), nullable=True),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('phone IS NOT NULL OR telegram IS NOT NULL OR external_url IS NOT NULL', name=op.f('ck_jobs_has_contact')),
    sa.CheckConstraint('title IS NOT NULL OR internal_ref IS NOT NULL', name=op.f('ck_jobs_has_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('public_id', name=op.f('uq_jobs_public_id')),
    schema='hirely'
    )
    op.create_index('ix_jobs_category', 'jobs', ['category'], unique=False, schema='hirely')
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False, schema='hirely')
    op.create_table('visitors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('anon_id', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitors')),
    sa.UniqueConstraint('anon_id', name=op.f('uq_visitors_anon_id')),
    schema='hirely'
    )
    op.create_table('ad_campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('advertiser_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='draft', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('impression_limit', sa.BigInteger(), nullable=True),
    sa.Column('click_limit', sa.BigInteger(), nullable=True),
    sa.Column('impressions_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('clicks_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','paused','archived')", name=op.f('ck_ad_campaigns_status')),
    sa.CheckConstraint('end_at IS NULL OR start_at IS NULL OR end_at > start_at', name=op.f('ck_ad_campaigns_period')),
    sa.ForeignKeyConstraint(['advertiser_id'], ['hirely.advertisers.id'], name=op.f('fk_ad_campaigns_advertiser_id_advertisers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_campaigns')),
    schema='hirely'
    )
    op.create_index('ix_ad_campaigns_status', 'ad_campaigns', ['status'], unique=False, schema='hirely')
    op.create_table('distributions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('slug', sa.String(length=12), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['hirely.channels.id'], name=op.f('fk_distributions_channel_id_channels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['hirely.jobs.id'], name=op.f('fk_distributions_job_id_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributions')),
    sa.UniqueConstraint('code', name=op.f('uq_distributions_code')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_distributions_idempotency_key')),
    sa.UniqueConstraint('slug', name=op.f('uq_distributions_slug')),
    schema='hirely'
    )
    op.create_index('ix_distributions_channel_created', 'distributions', ['channel_id', 'created_at'], unique=False, schema='hirely')
    op.create_index('ix_distributions_job_id', 'distributions', ['job_id'], unique=False, schema='hirely')
    op.create_table('ad_creatives',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('cta_text', sa.String(length=40), nullable=False),
    sa.Column('destination_url', sa.String(length=2048), nullable=False),
    sa.Column('image_name', sa.String(length=64), nullable=True),
    sa.Column('image_w', sa.SmallInteger(), nullable=True),
    sa.Column('image_h', sa.SmallInteger(), nullable=True),
    sa.Column('weight', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight BETWEEN 1 AND 100', name=op.f('ck_ad_creatives_weight')),
    sa.ForeignKeyConstraint(['campaign_id'], ['hirely.ad_campaigns.id'], name=op.f('fk_ad_creatives_campaign_id_ad_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_creatives')),
    schema='hirely'
    )
    op.create_index('ix_ad_creatives_campaign_id', 'ad_creatives', ['campaign_id'], unique=False, schema='hirely')
    op.create_table('ad_targets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.CheckConstraint("kind IN ('channel','category','market')", name=op.f('ck_ad_targets_kind')),
    sa.ForeignKeyConstraint(['campaign_id'], ['hirely.ad_campaigns.id'], name=op.f('fk_ad_targets_campaign_id_ad_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_targets')),
    sa.UniqueConstraint('campaign_id', 'kind', 'value', name='uq_ad_targets_campaign_kind_value'),
    schema='hirely'
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('visitor_id', sa.BigInteger(), nullable=False),
    sa.Column('distribution_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('referrer_host', sa.String(length=120), nullable=True),
    sa.Column('traffic_source', sa.String(length=60), nullable=True),
    sa.Column('device_category', sa.String(length=12), nullable=True),
    sa.Column('browser', sa.String(length=24), nullable=True),
    sa.Column('os', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['distribution_id'], ['hirely.distributions.id'], name=op.f('fk_sessions_distribution_id_distributions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['hirely.visitors.id'], name=op.f('fk_sessions_visitor_id_visitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('session_key', name=op.f('uq_sessions_session_key')),
    schema='hirely'
    )
    op.create_index('ix_sessions_started_at', 'sessions', ['started_at'], unique=False, schema='hirely')
    op.create_index('ix_sessions_visitor_id', 'sessions', ['visitor_id'], unique=False, schema='hirely')
    op.create_table('ad_clicks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creative_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('distribution_id', sa.BigInteger(), nullable=True),
    sa.Column('visitor_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('device_category', sa.String(length=12), nullable=True),
    sa.Column('impression_nonce', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['hirely.ad_campaigns.id'], name=op.f('fk_ad_clicks_campaign_id_ad_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_id'], ['hirely.ad_creatives.id'], name=op.f('fk_ad_clicks_creative_id_ad_creatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['distribution_id'], ['hirely.distributions.id'], name=op.f('fk_ad_clicks_distribution_id_distributions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['hirely.sessions.id'], name=op.f('fk_ad_clicks_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['hirely.visitors.id'], name=op.f('fk_ad_clicks_visitor_id_visitors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_clicks')),
    sa.UniqueConstraint('event_id', name=op.f('uq_ad_clicks_event_id')),
    schema='hirely'
    )
    op.create_index('ix_ad_clicks_campaign_occurred', 'ad_clicks', ['campaign_id', 'occurred_at'], unique=False, schema='hirely')
    op.create_index('ix_ad_clicks_creative_visitor', 'ad_clicks', ['creative_id', 'visitor_id'], unique=False, schema='hirely')
    op.create_index('ix_ad_clicks_occurred_brin', 'ad_clicks', ['occurred_at'], unique=False, schema='hirely', postgresql_using='brin')
    op.create_table('ad_impressions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nonce', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creative_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('distribution_id', sa.BigInteger(), nullable=True),
    sa.Column('visitor_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('device_category', sa.String(length=12), nullable=True),
    sa.Column('visible_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['hirely.ad_campaigns.id'], name=op.f('fk_ad_impressions_campaign_id_ad_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_id'], ['hirely.ad_creatives.id'], name=op.f('fk_ad_impressions_creative_id_ad_creatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['distribution_id'], ['hirely.distributions.id'], name=op.f('fk_ad_impressions_distribution_id_distributions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['hirely.sessions.id'], name=op.f('fk_ad_impressions_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['hirely.visitors.id'], name=op.f('fk_ad_impressions_visitor_id_visitors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_impressions')),
    sa.UniqueConstraint('nonce', name=op.f('uq_ad_impressions_nonce')),
    schema='hirely'
    )
    op.create_index('ix_ad_impressions_campaign_occurred', 'ad_impressions', ['campaign_id', 'occurred_at'], unique=False, schema='hirely')
    op.create_index('ix_ad_impressions_creative_visitor', 'ad_impressions', ['creative_id', 'visitor_id'], unique=False, schema='hirely')
    op.create_index('ix_ad_impressions_occurred_brin', 'ad_impressions', ['occurred_at'], unique=False, schema='hirely', postgresql_using='brin')
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('distribution_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('visitor_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('job_source', sa.String(length=40), nullable=True),
    sa.Column('traffic_source', sa.String(length=60), nullable=True),
    sa.Column('referrer_host', sa.String(length=120), nullable=True),
    sa.Column('device_category', sa.String(length=12), nullable=True),
    sa.Column('browser', sa.String(length=24), nullable=True),
    sa.Column('os', sa.String(length=24), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("type IN ('page_view','unique_visitor','session_start','phone_click','telegram_click','external_job_click','ad_impression','ad_click')", name=op.f('ck_events_type')),
    sa.ForeignKeyConstraint(['ad_id'], ['hirely.ad_creatives.id'], name=op.f('fk_events_ad_id_ad_creatives'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['hirely.ad_campaigns.id'], name=op.f('fk_events_campaign_id_ad_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['hirely.channels.id'], name=op.f('fk_events_channel_id_channels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['distribution_id'], ['hirely.distributions.id'], name=op.f('fk_events_distribution_id_distributions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['hirely.jobs.id'], name=op.f('fk_events_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['hirely.sessions.id'], name=op.f('fk_events_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['hirely.visitors.id'], name=op.f('fk_events_visitor_id_visitors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_events_event_id')),
    schema='hirely'
    )
    op.create_index('ix_events_campaign_type_occurred', 'events', ['campaign_id', 'type', 'occurred_at'], unique=False, schema='hirely', postgresql_where=sa.text('campaign_id IS NOT NULL'))
    op.create_index('ix_events_channel_type_occurred', 'events', ['channel_id', 'type', 'occurred_at'], unique=False, schema='hirely')
    op.create_index('ix_events_creative_type_occurred', 'events', ['ad_id', 'type', 'occurred_at'], unique=False, schema='hirely', postgresql_where=sa.text('ad_id IS NOT NULL'))
    op.create_index('ix_events_job_type_occurred', 'events', ['job_id', 'type', 'occurred_at'], unique=False, schema='hirely')
    op.create_index('ix_events_occurred_at_brin', 'events', ['occurred_at'], unique=False, schema='hirely', postgresql_using='brin')
    op.create_index('ix_events_type_occurred', 'events', ['type', 'occurred_at'], unique=False, schema='hirely')
    op.create_index('ix_events_visitor_type', 'events', ['visitor_id', 'type'], unique=False, schema='hirely')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_visitor_type', table_name='events', schema='hirely')
    op.drop_index('ix_events_type_occurred', table_name='events', schema='hirely')
    op.drop_index('ix_events_occurred_at_brin', table_name='events', schema='hirely', postgresql_using='brin')
    op.drop_index('ix_events_job_type_occurred', table_name='events', schema='hirely')
    op.drop_index('ix_events_creative_type_occurred', table_name='events', schema='hirely', postgresql_where=sa.text('ad_id IS NOT NULL'))
    op.drop_index('ix_events_channel_type_occurred', table_name='events', schema='hirely')
    op.drop_index('ix_events_campaign_type_occurred', table_name='events', schema='hirely', postgresql_where=sa.text('campaign_id IS NOT NULL'))
    op.drop_table('events', schema='hirely')
    op.drop_index('ix_ad_impressions_occurred_brin', table_name='ad_impressions', schema='hirely', postgresql_using='brin')
    op.drop_index('ix_ad_impressions_creative_visitor', table_name='ad_impressions', schema='hirely')
    op.drop_index('ix_ad_impressions_campaign_occurred', table_name='ad_impressions', schema='hirely')
    op.drop_table('ad_impressions', schema='hirely')
    op.drop_index('ix_ad_clicks_occurred_brin', table_name='ad_clicks', schema='hirely', postgresql_using='brin')
    op.drop_index('ix_ad_clicks_creative_visitor', table_name='ad_clicks', schema='hirely')
    op.drop_index('ix_ad_clicks_campaign_occurred', table_name='ad_clicks', schema='hirely')
    op.drop_table('ad_clicks', schema='hirely')
    op.drop_index('ix_sessions_visitor_id', table_name='sessions', schema='hirely')
    op.drop_index('ix_sessions_started_at', table_name='sessions', schema='hirely')
    op.drop_table('sessions', schema='hirely')
    op.drop_table('ad_targets', schema='hirely')
    op.drop_index('ix_ad_creatives_campaign_id', table_name='ad_creatives', schema='hirely')
    op.drop_table('ad_creatives', schema='hirely')
    op.drop_index('ix_distributions_job_id', table_name='distributions', schema='hirely')
    op.drop_index('ix_distributions_channel_created', table_name='distributions', schema='hirely')
    op.drop_table('distributions', schema='hirely')
    op.drop_index('ix_ad_campaigns_status', table_name='ad_campaigns', schema='hirely')
    op.drop_table('ad_campaigns', schema='hirely')
    op.drop_table('visitors', schema='hirely')
    op.drop_index('ix_jobs_created_at', table_name='jobs', schema='hirely')
    op.drop_index('ix_jobs_category', table_name='jobs', schema='hirely')
    op.drop_table('jobs', schema='hirely')
    op.drop_table('channels', schema='hirely')
    op.drop_table('advertisers', schema='hirely')
    op.drop_table('admins', schema='hirely')
    # ### end Alembic commands ###
