"""Add ai_usage_logs table

Revision ID: 04e2cafb962d
Revises: 006_seed_smart_flags
Create Date: 2025-12-16 23:05:10.137146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e2cafb962d'
down_revision: Union[str, None] = '006_seed_smart_flags'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feature', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_id'), 'ai_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    op.alter_column('admin_events', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_admin_events_created_at'), table_name='admin_events')
    op.drop_index(op.f('idx_admin_events_type_created'), table_name='admin_events')
    op.drop_index(op.f('idx_admin_events_user_created'), table_name='admin_events')
    op.create_index(op.f('ix_admin_events_created_at'), 'admin_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_events_event_type'), 'admin_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_admin_events_id'), 'admin_events', ['id'], unique=False)
    op.create_index(op.f('ix_admin_events_user_id'), 'admin_events', ['user_id'], unique=False)
    op.drop_column('bot_content', 'category')
    op.drop_index(op.f('idx_daily_logs_user_date'), table_name='daily_logs')
    op.drop_index(op.f('idx_users_active_points'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_active_points'), 'users', ['active', 'points'], unique=False)
    op.create_index(op.f('idx_daily_logs_user_date'), 'daily_logs', ['user_id', 'date'], unique=False)
    op.add_column('bot_content', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_admin_events_user_id'), table_name='admin_events')
    op.drop_index(op.f('ix_admin_events_id'), table_name='admin_events')
    op.drop_index(op.f('ix_admin_events_event_type'), table_name='admin_events')
    op.drop_index(op.f('ix_admin_events_created_at'), table_name='admin_events')
    op.create_index(op.f('idx_admin_events_user_created'), 'admin_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_admin_events_type_created'), 'admin_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('idx_admin_events_created_at'), 'admin_events', ['created_at'], unique=False)
    op.alter_column('admin_events', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_id'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    # ### end Alembic commands ###
