"""sync_models

Revision ID: 5819cbc5a6e7
Revises: f5af7248ea38
Create Date: 2026-06-03 19:14:14.783146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5819cbc5a6e7'
down_revision: Union[str, None] = 'f5af7248ea38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('campaign', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('referer_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('user_status', sa.String(length=20), nullable=False, server_default='started'))
    op.add_column('users', sa.Column('goal_tag', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('level_tag', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('lead_score', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('lead_segment', sa.String(length=20), nullable=True, server_default='content_only'))
    op.add_column('users', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2000'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_referral_code', table_name='users')
    op.create_index('ix_users_campaign', 'users', ['campaign'], unique=False)
    op.create_index('ix_users_lead_segment', 'users', ['lead_segment'], unique=False)
    op.create_index('ix_users_user_status', 'users', ['user_status'], unique=False)
    op.create_unique_constraint(None, 'users', ['phone_hash'])
    op.drop_constraint('fk_users_referrer', 'users', type_='foreignkey')
    op.drop_column('users', 'target_weight')
    op.drop_column('users', 'yasha_points')
    op.drop_column('users', 'trial_used')
    op.drop_column('users', 'notification_settings')
    op.drop_column('users', 'streak_workout')
    op.drop_column('users', 'ai_workout_count')
    op.drop_column('users', 'utm_source')
    op.drop_column('users', 'active')
    op.drop_column('users', 'premium_until')
    op.drop_column('users', 'ai_menu_count')
    op.drop_column('users', 'last_checkin')
    op.drop_column('users', 'trial_start')
    op.drop_column('users', 'allergies')
    op.drop_column('users', 'ai_last_reset_month')
    op.drop_column('users', 'streak_mood')
    op.drop_column('users', 'language')
    op.drop_column('users', 'streak_sleep')
    op.drop_column('users', 'calorie_daily_uses')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'utm_raw')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'height')
    op.drop_column('users', 'points')
    op.drop_column('users', 'onboarding_data')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'calorie_last_use_date')
    op.drop_column('users', 'elixir')
    op.drop_column('users', 'referrer_id')
    op.drop_column('users', 'onboarding_state')
    op.drop_column('users', 'plan_type')
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'utm_campaign')
    op.drop_column('users', 'chat_daily_uses')
    op.drop_column('users', 'goal')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'auto_renew')
    op.drop_column('users', 'streak_water')
    op.drop_column('users', 'daily_stats')
    op.drop_column('users', 'chat_last_use_date')
    op.drop_column('users', 'is_onboarded')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_onboarded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('chat_last_use_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('daily_stats', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('streak_water', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('auto_renew', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('chat_daily_uses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('utm_campaign', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('activity_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('plan_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('onboarding_state', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('referrer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('elixir', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('calorie_last_use_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('onboarding_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('utm_raw', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('calorie_daily_uses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('streak_sleep', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('language', sa.VARCHAR(), server_default=sa.text("'uz'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('streak_mood', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ai_last_reset_month', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('allergies', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('trial_start', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_checkin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ai_menu_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('premium_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('utm_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ai_workout_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('streak_workout', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('notification_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('trial_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('yasha_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('target_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_users_referrer', 'users', 'users', ['referrer_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_user_status', table_name='users')
    op.drop_index('ix_users_lead_segment', table_name='users')
    op.drop_index('ix_users_campaign', table_name='users')
    op.create_index('ix_users_referral_code', 'users', ['referral_code'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2000'))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('users', 'registered_at')
    op.drop_column('users', 'lead_segment')
    op.drop_column('users', 'lead_score')
    op.drop_column('users', 'level_tag')
    op.drop_column('users', 'goal_tag')
    op.drop_column('users', 'user_status')
    op.drop_column('users', 'referer_id')
    op.drop_column('users', 'campaign')
    op.drop_column('users', 'source')
    op.drop_column('users', 'phone_hash')
    # ### end Alembic commands ###
