"""add_user_adaptation_state

Revision ID: 592cebfc6e34
Revises: df6d029cc302
Create Date: 2025-12-27 15:14:46.343746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592cebfc6e34'
down_revision: Union[str, None] = 'df6d029cc302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_adaptation_state',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_variant_preference', sa.String(), nullable=True),
    sa.Column('menu_kcal_adjust_pct', sa.Float(), nullable=True),
    sa.Column('menu_complexity_level', sa.Integer(), nullable=True),
    sa.Column('workout_soft_mode', sa.Boolean(), nullable=True),
    sa.Column('coach_priority_mode', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_adaptation_state')
    # ### end Alembic commands ###
