"""Add optimization tables and featured column

Revision ID: 5d2dec547cfb
Revises: 592cebfc6e34
Create Date: 2025-12-27 16:09:54.126343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2dec547cfb'
down_revision: Union[str, None] = '592cebfc6e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('admin_override', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_logs_created_at'), 'optimization_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_optimization_logs_id'), 'optimization_logs', ['id'], unique=False)
    op.create_table('dish_review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['local_dishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id', 'reason', name='uq_dish_reason_open')
    )
    op.create_index(op.f('ix_dish_review_queue_created_at'), 'dish_review_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_dish_review_queue_id'), 'dish_review_queue', ['id'], unique=False)
    op.add_column('local_dishes', sa.Column('featured', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_local_dishes_featured'), 'local_dishes', ['featured'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_local_dishes_featured'), table_name='local_dishes')
    op.drop_column('local_dishes', 'featured')
    op.drop_index(op.f('ix_dish_review_queue_id'), table_name='dish_review_queue')
    op.drop_index(op.f('ix_dish_review_queue_created_at'), table_name='dish_review_queue')
    op.drop_table('dish_review_queue')
    op.drop_index(op.f('ix_optimization_logs_id'), table_name='optimization_logs')
    op.drop_index(op.f('ix_optimization_logs_created_at'), table_name='optimization_logs')
    op.drop_table('optimization_logs')
    # ### end Alembic commands ###
