"""add knowledge_base table

Revision ID: 6b2e02e7c0fa
Revises: bf5fa884d9f0
Create Date: 2025-12-29 03:29:52.629129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2e02e7c0fa'
down_revision: Union[str, None] = 'bf5fa884d9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    if not inspector.has_table('knowledge_base'):
        op.create_table('knowledge_base',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('answer', sa.Text(), nullable=False),
        sa.Column('topic', sa.String(), nullable=True),
        sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
        op.create_index(op.f('ix_knowledge_base_question'), 'knowledge_base', ['question'], unique=False)
    else:
        print("Table 'knowledge_base' already exists, skipping creation.")

    # Seed initial 100 Q&A pairs
    import json
    import os
    try:
        base_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        db_path = os.path.join(base_path, "bot", "data", "ai_qa_db.json")
        if os.path.exists(db_path):
            with open(db_path, "r", encoding="utf-8") as f:
                qa_data = json.load(f)
                
            knowledge_base = sa.table('knowledge_base',
                sa.column('question', sa.Text),
                sa.column('answer', sa.Text),
                sa.column('topic', sa.String),
                sa.column('is_ai_generated', sa.Boolean),
                sa.column('created_at', sa.DateTime)
            )
            
            # Group by 50 to avoid massive single insert if needed, but 100 is fine
            rows = []
            from datetime import datetime
            for item in qa_data:
                rows.append({
                    'question': item.get('question'),
                    'answer': item.get('answer'),
                    'topic': item.get('topic'),
                    'is_ai_generated': False,
                    'created_at': datetime.utcnow()
                })
            
            if rows:
                op.bulk_insert(knowledge_base, rows)
    except Exception as e:
        print(f"Warning: Could not seed knowledge_base: {e}")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_question'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
