"""add_user_notification_settings_and_language

Revision ID: 9d3421b04a36
Revises: 5d2dec547cfb
Create Date: 2025-12-28 00:26:53.461476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3421b04a36'
down_revision: Union[str, None] = '5d2dec547cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.String(), nullable=True, server_default='uz'))
    op.add_column('users', sa.Column('notification_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_settings')
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
