"""add_video_workout_fields

Revision ID: bf5fa884d9f0
Revises: fbea96d98218
Create Date: 2025-12-28 16:35:22.132668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5fa884d9f0'
down_revision: Union[str, None] = 'fbea96d98218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    def safe_add_column(table_name, column):
        conn = op.get_bind()
        res = conn.execute(sa.text(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name = :table_name AND column_name = :column_name"
        ), {"table_name": table_name, "column_name": column.name})
        if res.scalar() is None:
            op.add_column(table_name, column)

    def safe_create_index(index_name, table_name, columns, unique=False):
        conn = op.get_bind()
        res = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = :indexname"), {"indexname": index_name})
        if res.scalar() is None:
            op.create_index(index_name, table_name, columns, unique=unique)

    safe_add_column('exercises', sa.Column('equipment', sa.String(), nullable=True))
    safe_add_column('exercises', sa.Column('muscle_group', sa.String(), nullable=True))
    safe_add_column('exercises', sa.Column('level', sa.String(), nullable=True))
    safe_add_column('exercises', sa.Column('place', sa.String(), nullable=True))
    safe_add_column('exercises', sa.Column('duration_sec', sa.Integer(), nullable=True))
    
    safe_create_index('ix_exercises_equipment', 'exercises', ['equipment'], unique=False)
    safe_create_index('ix_exercises_level', 'exercises', ['level'], unique=False)
    safe_create_index('ix_exercises_muscle_group', 'exercises', ['muscle_group'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_muscle_group'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_level'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment'), table_name='exercises')
    
    op.drop_column('exercises', 'duration_sec')
    op.drop_column('exercises', 'place')
    op.drop_column('exercises', 'level')
    op.drop_column('exercises', 'muscle_group')
    op.drop_column('exercises', 'equipment')
    # ### end Alembic commands ###
