"""add_feedback_tables

Revision ID: df6d029cc302
Revises: aed3f63d0664
Create Date: 2025-12-27 15:05:17.670978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df6d029cc302'
down_revision: Union[str, None] = 'aed3f63d0664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check existing tables to avoid DuplicateTable error
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'coach_feedback' not in existing_tables:
        op.create_table('coach_feedback',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('coach_msg_key', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('reaction', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_coach_feedback_coach_msg_key'), 'coach_feedback', ['coach_msg_key'], unique=False)
        op.create_index(op.f('ix_coach_feedback_created_at'), 'coach_feedback', ['created_at'], unique=False)
        op.create_index(op.f('ix_coach_feedback_id'), 'coach_feedback', ['id'], unique=False)
        op.create_index(op.f('ix_coach_feedback_user_id'), 'coach_feedback', ['user_id'], unique=False)
    
    if 'menu_feedback' not in existing_tables:
        op.create_table('menu_feedback',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('menu_template_id', sa.Integer(), nullable=True),
        sa.Column('day_index', sa.Integer(), nullable=True),
        sa.Column('rating', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_menu_feedback_created_at'), 'menu_feedback', ['created_at'], unique=False)
        op.create_index(op.f('ix_menu_feedback_id'), 'menu_feedback', ['id'], unique=False)
        op.create_index(op.f('ix_menu_feedback_menu_template_id'), 'menu_feedback', ['menu_template_id'], unique=False)
        op.create_index(op.f('ix_menu_feedback_user_id'), 'menu_feedback', ['user_id'], unique=False)
    
    if 'workout_feedback' not in existing_tables:
        op.create_table('workout_feedback',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('workout_plan_id', sa.Integer(), nullable=True),
        sa.Column('day_index', sa.Integer(), nullable=True),
        sa.Column('rating', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_workout_feedback_created_at'), 'workout_feedback', ['created_at'], unique=False)
        op.create_index(op.f('ix_workout_feedback_id'), 'workout_feedback', ['id'], unique=False)
        op.create_index(op.f('ix_workout_feedback_user_id'), 'workout_feedback', ['user_id'], unique=False)
        op.create_index(op.f('ix_workout_feedback_workout_plan_id'), 'workout_feedback', ['workout_plan_id'], unique=False)
    op.drop_index(op.f('ix_local_dish_ingredients_dish_id'), table_name='local_dish_ingredients')
    op.create_index(op.f('ix_local_dish_ingredients_id'), 'local_dish_ingredients', ['id'], unique=False)
    op.alter_column('local_dishes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('local_dishes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_local_dishes_goal_meal_variant_active'), table_name='local_dishes')
    op.drop_constraint(op.f('uq_local_dishes_name_portion_variant'), 'local_dishes', type_='unique')
    op.create_index(op.f('ix_local_dishes_id'), 'local_dishes', ['id'], unique=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('workout_plans', 'days_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('workout_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('workout_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_workout_plans_goal_level_place_active'), table_name='workout_plans')
    op.create_index(op.f('ix_workout_plans_id'), 'workout_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_plans_id'), table_name='workout_plans')
    op.create_index(op.f('ix_workout_plans_goal_level_place_active'), 'workout_plans', ['goal_tag', 'level', 'place', 'is_active'], unique=False)
    op.alter_column('workout_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('workout_plans', 'days_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('users', 'is_onboarded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_local_dishes_id'), table_name='local_dishes')
    op.create_unique_constraint(op.f('uq_local_dishes_name_portion_variant'), 'local_dishes', ['name_uz', 'portion_type', 'variant'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_local_dishes_goal_meal_variant_active'), 'local_dishes', ['goal_tag', 'meal_type', 'variant', 'is_active'], unique=False)
    op.alter_column('local_dishes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('local_dishes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_local_dish_ingredients_id'), table_name='local_dish_ingredients')
    op.create_index(op.f('ix_local_dish_ingredients_dish_id'), 'local_dish_ingredients', ['dish_id'], unique=False)
    op.drop_index(op.f('ix_workout_feedback_workout_plan_id'), table_name='workout_feedback')
    op.drop_index(op.f('ix_workout_feedback_user_id'), table_name='workout_feedback')
    op.drop_index(op.f('ix_workout_feedback_id'), table_name='workout_feedback')
    op.drop_index(op.f('ix_workout_feedback_created_at'), table_name='workout_feedback')
    op.drop_table('workout_feedback')
    op.drop_index(op.f('ix_menu_feedback_user_id'), table_name='menu_feedback')
    op.drop_index(op.f('ix_menu_feedback_menu_template_id'), table_name='menu_feedback')
    op.drop_index(op.f('ix_menu_feedback_id'), table_name='menu_feedback')
    op.drop_index(op.f('ix_menu_feedback_created_at'), table_name='menu_feedback')
    op.drop_table('menu_feedback')
    op.drop_index(op.f('ix_coach_feedback_user_id'), table_name='coach_feedback')
    op.drop_index(op.f('ix_coach_feedback_id'), table_name='coach_feedback')
    op.drop_index(op.f('ix_coach_feedback_created_at'), table_name='coach_feedback')
    op.drop_index(op.f('ix_coach_feedback_coach_msg_key'), table_name='coach_feedback')
    op.drop_table('coach_feedback')
    # ### end Alembic commands ###
