"""verify_schema_v3

Revision ID: fbea96d98218
Revises: c04bbd5ec056
Create Date: 2025-12-28 16:27:34.081202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbea96d98218'
down_revision: Union[str, None] = 'c04bbd5ec056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_usage_lookup'), table_name='usage_counters')
    op.create_index(op.f('ix_usage_counters_id'), 'usage_counters', ['id'], unique=False)
    op.create_index(op.f('ix_usage_counters_user_id'), 'usage_counters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_counters_user_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_id'), table_name='usage_counters')
    op.create_index(op.f('idx_usage_lookup'), 'usage_counters', ['user_id', 'feature_key', 'period_start'], unique=False)
    # ### end Alembic commands ###
