"""add daily report

Revision ID: ff0000000002
Revises: ff0000000001
Create Date: 2026-04-11 14:14:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ff0000000002'
down_revision = 'ff0000000001'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amocrm_user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.String(length=50), nullable=True),
    sa.Column('amo_call_time', sa.String(length=50), nullable=True),
    sa.Column('phone_call_time', sa.String(length=50), nullable=True),
    sa.Column('leads_received', sa.Integer(), nullable=True),
    sa.Column('calls_answered', sa.Integer(), nullable=True),
    sa.Column('calls_missed', sa.Integer(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('sales_won', sa.Integer(), nullable=True),
    sa.Column('pre_payments', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_amocrm_user_id'), 'daily_reports', ['amocrm_user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_reports_amocrm_user_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
