import React, { createContext, useState, useCallback, useContext, useEffect } from 'react';
import { useUser } from './UserContext';

export type Language = 'uz' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    // Common
    'common.save': 'Saqlash',
    'common.cancel': 'Bekor qilish',
    'common.back': 'Orqaga',
    'common.next': 'Keyingi',
    'common.done': 'Bajarildi',
    'common.add': 'Qo\'shish',
    'common.delete': 'O\'chirish',
    'common.edit': 'Tahrirlash',
    'common.loading': 'Yuklanmoqda...',
    'common.error': 'Xato',
    'common.success': 'Muvaffaqiyatli',
    'common.today': 'Bugun',
    'common.days': 'kun',
    'common.hours': 'soat',
    'common.minutes': 'daqiqa',
    'common.all': 'Hammasi',
    'common.day': 'Kun',

    // Days of week
    'day.mon': 'Du',
    'day.tue': 'Se',
    'day.wed': 'Cho',
    'day.thu': 'Pa',
    'day.fri': 'Ju',
    'day.sat': 'Sha',
    'day.sun': 'Ya',

    // Navigation
    'nav.home': 'Bosh sahifa',
    'nav.explore': 'Yana',
    'nav.menu': 'Ovqat',
    'nav.workout': 'Mashq',
    'nav.profile': 'Profil',

    // Home Screen
    'home.greeting': 'Salom',
    'home.howAreYou': 'Bugun qanday kayfiyat?',
    'home.todayResults': 'Bugungi natijalar',
    'home.streaks': 'Seriyalar',
    'home.aiCoach': 'AI Murabbiy',
    'home.personalAdvice': 'Shaxsiy maslahat',
    'home.dailyHabits': 'Kundalik odatlar',
    'home.waterSleepSteps': 'Suv, uyqu, qadam',
    'home.exploreMore': 'Yana ko\'proq',
    'home.friendsCompetition': 'Do\'stlar, raqobat, do\'kon',
    'home.trialPeriod': 'Sinov muddati',
    'home.daysRemaining': 'kun qoldi',
    'home.user': 'Foydalanuvchi',

    // Stats
    'stats.water': 'Suv',
    'stats.calories': 'Kaloriya',
    'stats.sleep': 'Uyqu',
    'stats.workout': 'Mashq',
    'stats.steps': 'Qadamlar',
    'stats.mood': 'Kayfiyat',
    'stats.completed': 'Bajarildi',
    'stats.pending': 'Kutilmoqda',

    // Menu Screen
    'menu.title': 'Kunlik menyu',
    'menu.weekly': '7 kunlik',
    'menu.dailyTotal': 'Kunlik kaloriya',
    'menu.consumed': 'iste\'mol qilingan',
    'menu.recommended': 'tavsiya etilgan',
    'menu.remaining': 'qoldi',
    'menu.excess': 'ortiqcha',
    'menu.actual': 'Haqiqiy',
    'menu.actualData': 'Haqiqiy ma\'lumot',
    'menu.breakfast': 'Nonushta',
    'menu.lunch': 'Tushlik',
    'menu.dinner': 'Kechki ovqat',
    'menu.snack': 'Tamaddi',
    'menu.tip': 'Maslahat',
    'menu.tipText': 'Kuniga kamida 2 litr suv iching va ovqatlanish orasida 3-4 soat oraliq saqlang.',
    'menu.premiumInfo': 'Bepul rejada faqat bugungi menyu mavjud. AI shaxsiy menyu uchun Premium kerak.',
    'menu.protein': 'oqsil',
    'menu.carbs': 'uglevod',
    'menu.fat': 'yog\'',
    'menu.iAteIt': 'Iste\'mol qildim',
    'menu.mealAddedSuccess': 'Ovqat kundalikka qo\'shildi!',

    // Workout Screen
    'workout.title': 'Mashqlar',
    'workout.videoWorkouts': 'Video mashqlar',
    'workout.comingSoon': 'Tez kunda',
    'workout.videosSoon': 'Video mashqlar tez orada qo\'shiladi',
    'workout.warmupTip': 'Har bir mashqdan oldin 5 daqiqa isitish mashqlari qiling. Bu jarohatlarning oldini oladi.',
    'workout.premiumInfo': 'Bepul rejada 3 ta asosiy mashq mavjud. AI shaxsiy dastur uchun Premium kerak.',
    'workout.homeBasic': 'Uyda mashq - Boshlang\'ich',
    'workout.cardioStretching': 'Kardio va stretching',
    'workout.upperBody': 'Tananing yuqori qismi',
    'workout.homeCardio': 'Uyda kardio mashqi',
    'workout.abs': 'Qorin mushaklari',
    'workout.fullBody': 'Butun tana mashqi',

    // Habits Screen
    'habits.title': 'Kundalik odatlar',
    'habits.subtitle': 'Sog\'lom odatlarni kuzatib boring',
    'habits.waterIntake': 'Suv ichish',
    'habits.steps': 'Qadamlar',
    'habits.sleep': 'Uyqu',
    'habits.dailyTip': 'Kunlik maslahat',
    'habits.dailyTipText': 'Har soatda 1 stakan suv iching. Bu metabolizmni tezlashtiradi va energiya beradi!',
    'habits.todayMood': 'Bugungi kayfiyat',
    'habits.moodBad': 'Yomon',
    'habits.moodOk': 'O\'rtacha',
    'habits.moodGood': 'Yaxshi',
    'habits.waterAdded': '+250 ml suv qo\'shildi!',
    'habits.stepsAdded': 'qadam qo\'shildi!',
    'habits.sleepSaved': 'soat uyqu saqlandi!',
    'habits.badMoodMsg1': 'Hamma narsa yaxshi bo\'ladi! Bugun o\'zingizga ko\'proq e\'tibor bering.',
    'habits.badMoodMsg2': 'Qiyin kunlar ham o\'tadi. Siz kuchlisiz!',
    'habits.badMoodMsg3': 'Har bir kun yangi imkoniyat. Ertaga yaxshiroq bo\'ladi!',
    'habits.goodMoodMsg': 'Ajoyib! Bugun yaxshi kun!',

    // Profile Screen
    'profile.title': 'Profil',
    'profile.personalInfo': 'Shaxsiy ma\'lumotlar',
    'profile.age': 'Yosh',
    'profile.height': 'Bo\'y',
    'profile.weight': 'Vazn',
    'profile.goal': 'Maqsad',
    'profile.settings': 'Sozlamalar',
    'profile.settingsLang': 'Sozlamalar va til',
    'profile.notifications': 'Bildirishnomalar',
    'profile.language': 'Til',
    'profile.theme': 'Mavzu',
    'profile.privacy': 'Maxfiylik',
    'profile.help': 'Yordam',
    'profile.editProfile': 'Profilni tahrirlash',
    'profile.logout': 'Chiqish',

    // Calories Screen
    'calories.title': 'Kaloriya',
    'calories.dailyJournal': 'Kunlik jurnal',
    'calories.addMeal': 'Ovqat qo\'shish',
    'calories.todayCalories': 'Bugungi kaloriya',
    'calories.remaining': 'Qoldi',
    'calories.protein': 'Oqsil',
    'calories.carbs': 'Uglevod',
    'calories.fat': 'Yog\'',
    'calories.todayMeals': 'Bugungi ovqatlar',
    'calories.noMeals': 'Hali ovqat qo\'shilmagan',
    'calories.addMealHint': '+ tugmasini bosib ovqat qo\'shing',
    'calories.mealName': 'Ovqat nomi',
    'calories.mealType': 'Ovqat turi',
    'calories.mealAdded': 'Qo\'shildi!',
    'calories.mealDeleted': 'O\'chirildi',
    'calories.mealDeletedDesc': 'Ovqat o\'chirildi',
    'calories.requiredFields': 'Nom va kaloriya kiritilishi shart',
    'calories.gazak': 'Gazak',

    // Recipes Screen
    'recipes.title': 'Retseptlar',
    'recipes.subtitle': 'Sog\'lom taomlar',
    'recipes.ingredients': 'Ingredientlar',
    'recipes.preparation': 'Tayyorlash',
    'recipes.kcal': 'kkal',
    'recipes.time': 'vaqt',
    'recipes.servings': 'porsiya',

    // Daily Tasks
    'tasks.title': 'Kundalik Topshiriqlar',
    'tasks.completed': 'bajarildi',
    'tasks.yourLevel': 'Sizning levelingiz',
    'tasks.level': 'Level',
    'tasks.next': 'Keyingi',
    'tasks.points': 'ball',
    'tasks.allCompleted': 'Barcha topshiriqlar bajarildi!',
    'tasks.greatJob': 'Ajoyib ish!',
    'tasks.bonus': 'bonus',
    'tasks.todayTasks': 'Bugungi topshiriqlar',
    'tasks.claimReward': 'Mukofotni olish',
    'tasks.rewardClaimed': 'Mukofot olingan',
    'tasks.rewardReceived': 'Mukofot olindi!',
    'tasks.progress': 'Progress',
    'tasks.drinkWater': '2.5L suv ich',
    'tasks.drinkWaterDesc': 'Kunlik suv maqsadingizga erishing',
    'tasks.walk10k': '10,000 qadam',
    'tasks.walk10kDesc': 'Bugun 10 ming qadam yuring',
    'tasks.doWorkout': 'Mashq qiling',
    'tasks.doWorkoutDesc': 'Kamida bitta mashq bajaring',
    'tasks.sleep8h': '8 soat uxlang',
    'tasks.sleep8hDesc': 'Sifatli uyqu oling',
    'tasks.eat3meals': '3 ta ovqat',
    'tasks.eat3mealsDesc': 'Uchta sog\'lom ovqat yeng',

    // Settings
    'settings.title': 'Sozlamalar',
    'settings.language': 'Til',
    'settings.uzbek': 'O\'zbekcha',
    'settings.russian': 'Ruscha',
    'settings.theme': 'Mavzu',
    'settings.dark': 'Qorong\'u',
    'settings.light': 'Yorug\'',
    'settings.system': 'Tizim',

    // Paywall
    'paywall.title': 'Premium kerak',
    'paywall.feature': 'Bu funksiya uchun Premium talab qilinadi',
    'paywall.upgrade': 'Imkoniyatlarni kengaytirish',
    'paywall.later': 'Keyinroq',
    'paywall.aiMenu': 'AI menyu rejasi',
    'paywall.aiWorkout': 'AI mashq dasturi',

    // Explore Screen
    'explore.title': 'Yana ko\'proq',
    'explore.subtitle': 'Barcha xususiyatlar bir joyda',
    'explore.tracking': 'Kuzatish',
    'explore.wellness': 'Sog\'liq',
    'explore.social': 'Ijtimoiy',
    'explore.rewards': 'Mukofotlar',
    'explore.weight': 'Vazn',
    'explore.weightDesc': 'Vazn tarixi',
    'explore.calories': 'Kaloriya',
    'explore.caloriesDesc': 'Kunlik hisob',
    'explore.tasks': 'Topshiriqlar',
    'explore.tasksDesc': 'Kunlik vazifalar',
    'explore.reports': 'Hisobotlar',
    'explore.reportsDesc': 'Statistika',
    'explore.workouts': 'Mashqlar',
    'explore.workoutsDesc': 'Video darslar',
    'explore.meditation': 'Meditatsiya',
    'explore.meditationDesc': 'Tinchlanish',
    'explore.recipes': 'Retseptlar',
    'explore.recipesDesc': 'Sog\'lom taom',
    'explore.friends': 'Do\'stlar',
    'explore.friendsDesc': 'Reytinglar',
    'explore.challenges': 'Chellenjlar',
    'explore.challengesDesc': "Do'stlar bilan bellashuv",
    'explore.referrals': 'Referallar',
    'explore.referralsDesc': "Do'stlarni chaqiring",
    'explore.achievements': 'Yutuqlar',
    'explore.achievementsDesc': 'Medallar',
    'explore.shop': 'Do\'kon',
    'explore.shopDesc': 'Sovg\'alar',

    // Weight Screen
    'weight.title': 'Vazn',
    'weight.subtitle': 'Vazningizni kuzating',
    'weight.current': 'Hozirgi vazn',
    'weight.change': 'O\'zgarish',
    'weight.goal': 'Maqsad',
    'weight.last14days': 'So\'nggi 14 kun',
    'weight.history': 'Tarix',
    'weight.saved': 'Vazn saqlandi!',
    'weight.invalidWeight': 'To\'g\'ri vazn kiriting (30-300 kg)',
    'weight.placeholder': 'Vazn (kg)',

    // Reports Screen
    'reports.title': 'Hisobotlar',
    'reports.subtitle': 'Haftalik statistika',
    'reports.totalWater': 'Jami suv',
    'reports.totalSteps': 'Jami qadamlar',
    'reports.avgSleep': 'O\'rtacha uyqu',
    'reports.goalDays': 'Maqsad kunlari',
    'reports.waterChart': 'Suv (100ml)',
    'reports.stepsChart': 'Qadamlar (ming)',
    'reports.weeklyAnalysis': 'Haftalik tahlil',
    'reports.great': 'Ajoyib! Siz maqsadlaringizga yetib boryapsiz. Davom eting!',
    'reports.good': 'Yaxshi! Yana bir oz harakat va maqsadga yetasiz!',
    'reports.start': 'Har bir kun muhim. Kichik qadamlar bilan boshlang!',

    // Workout Library Screen
    'workoutLib.title': 'Mashqlar',
    'workoutLib.subtitle': 'Video kutubxona va timer',
    'workoutLib.all': 'Hammasi',
    'workoutLib.hiit': 'HIIT',
    'workoutLib.strength': 'Kuch',
    'workoutLib.yoga': 'Yoga',
    'workoutLib.cardio': 'Kardio',
    'workoutLib.flexibility': 'Moslashuvchanlik',
    'workoutLib.beginner': 'Boshlang\'ich',
    'workoutLib.intermediate': 'O\'rta',
    'workoutLib.advanced': 'Ilg\'or',
    'workoutLib.min': 'daq',
    'workoutLib.recommendation': 'Tavsiya',
    'workoutLib.calorie': 'Kaloriya',
    'workoutLib.completed': 'Mashq yakunlandi!',
    'workoutLib.caloriesBurned': 'kcal yoqildi',
    'workoutLib.morningStretch': 'Ertalabki cho\'zish',
    'workoutLib.morningStretchDesc': 'Kun boshlanishida tanani uyg\'otish',
    'workoutLib.hiitCardio': 'HIIT Cardio',
    'workoutLib.hiitCardioDesc': 'Yuqori intensivlikdagi interval mashq',
    'workoutLib.strengthTraining': 'Kuch mashqlari',
    'workoutLib.strengthTrainingDesc': 'Butun tana uchun kuch mashqlari',
    'workoutLib.yogaBasics': 'Yoga Asoslari',
    'workoutLib.yogaBasicsDesc': 'Boshlang\'ichlar uchun yoga',
    'workoutLib.absWorkout': 'Qorin presslari',
    'workoutLib.absWorkoutDesc': 'Qorin mushaklari uchun mashqlar',
    'workoutLib.tabata': 'Tabata Training',
    'workoutLib.tabataDesc': '4 daqiqalik intensiv mashq',

    // Meditation Screen
    'meditation.title': 'Meditatsiya',
    'meditation.subtitle': 'Nafas mashqlari',
    'meditation.relaxing': 'Tinchlanish',
    'meditation.relaxingDesc': '4-7-8 nafas texnikasi',
    'meditation.energizing': 'Kuch olish',
    'meditation.energizingDesc': 'Tez nafas olish',
    'meditation.calm': 'Orom',
    'meditation.calmDesc': 'Chuqur nafas olish',
    'meditation.inhale': 'Nafas oling',
    'meditation.hold': 'Ushlab turing',
    'meditation.exhale': 'Chiqaring',
    'meditation.rest': 'Dam oling',
    'meditation.cycles': 'Sikllar',
    'meditation.tip': 'Maslahat',
    'meditation.relaxingTip': 'Uxlashdan oldin ishlating. Stressni kamaytiradi.',
    'meditation.energizingTip': 'Ertalab yoki charchaganda ishlating. Energiya beradi.',
    'meditation.calmTip': 'Istalgan vaqtda stressni kamaytirish uchun ishlating.',

    // Friends Screen
    'friends.title': 'Do\'stlar',
    'friends.subtitle': 'Raqobatlashing va g\'alaba qozing!',
    'friends.search': 'Foydalanuvchi qidirish...',
    'friends.friendsTab': 'Do\'stlar',
    'friends.leaderboard': 'Reyting',
    'friends.online': 'Online',
    'friends.offline': 'Offline',
    'friends.challenge': 'Challenge',
    'friends.requestSent': 'So\'rov yuborildi',
    'friends.requestSentDesc': 'ga do\'stlik so\'rovi yuborildi',
    'friends.challengeSent': 'Challenge yuborildi!',
    'friends.challengeSentDesc': 'ga challenge yuborildi',
    'friends.enterUsername': 'Iltimos, foydalanuvchi nomini kiriting',
    'friends.you': 'Siz',

    // Challenges Screen
    'challenges.title': 'Challenge\'lar',
    'challenges.subtitle': 'Raqobatlashing va yutib chiqing!',
    'challenges.active': 'Faol Challenge\'lar',
    'challenges.new': 'Yangi Challenge',
    'challenges.name': 'Challenge nomi',
    'challenges.type': 'Turi',
    'challenges.targetValue': 'Maqsad qiymati',
    'challenges.duration': 'Davomiyligi',
    'challenges.create': 'Yaratish',
    'challenges.join': 'Qo\'shilish',
    'challenges.progress': 'Progress',
    'challenges.participants': 'ishtirokchi',
    'challenges.daysLeft': 'kun qoldi',
    'challenges.steps': 'Qadamlar',
    'challenges.water': 'Suv',
    'challenges.workouts': 'Mashqlar',
    'challenges.weight': 'Vazn',
    'challenges.step': 'qadam',
    'challenges.workout': 'mashq',
    'challenges.created': 'Challenge yaratildi!',
    'challenges.createdDesc': 'challenge muvaffaqiyatli yaratildi',
    'challenges.joined': 'Qo\'shildingiz!',
    'challenges.joinedDesc': 'challenge\'ga qo\'shildingiz',
    'challenges.fillAll': 'Barcha maydonlarni to\'ldiring',
    'challenges.3days': '3 kun',
    'challenges.7days': '7 kun',
    'challenges.14days': '14 kun',
    'challenges.30days': '30 kun',

    // Achievements Screen
    'achievements.title': 'Yutuqlar',
    'achievements.subtitle': 'Badjelar va mukofotlar',
    'achievements.badges': 'Badjelar',
    'achievements.points': 'Ballar',
    'achievements.waterStarter': 'Suv ichuvchi',
    'achievements.waterStarterDesc': 'Birinchi kun suv maqsadiga yetdi',
    'achievements.waterMaster': 'Suv ustasi',
    'achievements.waterMasterDesc': '7 kun ketma-ket suv maqsadiga yetdi',
    'achievements.stepCounter': 'Qadamshumor',
    'achievements.stepCounterDesc': '10,000 qadamga yetdi',
    'achievements.sleepMaster': 'Uyqu ustasi',
    'achievements.sleepMasterDesc': '7 kun 8 soat uxladi',
    'achievements.fireStreak': 'Olovli seriya',
    'achievements.fireStreakDesc': '14 kunlik seriyaga yetdi',
    'achievements.starCollector': 'Yulduz yig\'uvchi',
    'achievements.starCollectorDesc': '100 ball to\'pladi',
    'achievements.goldenCup': 'Oltin kubok',
    'achievements.goldenCupDesc': '500 ball to\'pladi',
    'achievements.perfectDay': 'Ideal kun',
    'achievements.perfectDayDesc': 'Barcha kunlik maqsadlarga yetdi',
    'achievements.1dayWater': '1 kun suv',
    'achievements.7dayStreak': '7 kun seriya',
    'achievements.10kSteps': '10,000 qadam',
    'achievements.14daysStreak': '14 kun ketma-ket',
    'achievements.100points': '100 ball',
    'achievements.500points': '500 ball',
    'achievements.allGoals': 'Suv, uyqu, qadam',

    // Shop Screen
    'shop.title': 'Do\'kon',
    'shop.subtitle': 'Tangalaringizni sarflang',
    'shop.all': 'Hammasi',
    'shop.frames': 'Ramkalar',
    'shop.themes': 'Temalar',
    'shop.boosts': 'Boostlar',
    'shop.owned': 'Bor',
    'shop.buy': 'Olish',
    'shop.alreadyOwned': 'Allaqachon sotib olingan',
    'shop.alreadyOwnedDesc': 'Bu mahsulot sizda bor',
    'shop.notEnough': 'Tangalar yetarli emas',
    'shop.notEnoughDesc': 'Bu mahsulot uchun tanga kerak',
    'shop.success': 'Xarid muvaffaqiyatli!',
    'shop.purchased': 'sotib olindi',
    'shop.goldenFrame': 'Oltin ramka',
    'shop.goldenFrameDesc': 'Profilingiz uchun oltin ramka',
    'shop.darkTheme': 'Qorong\'u tema',
    'shop.darkThemeDesc': 'Maxsus qorong\'u dizayn',
    'shop.xpBoost': '2x XP Boost',
    'shop.xpBoostDesc': '24 soat davomida 2 barobar XP',
    'shop.championBadge': 'Chempion nishoni',
    'shop.championBadgeDesc': 'Maxsus chempion nishoni',
    'shop.silverFrame': 'Kumush ramka',
    'shop.silverFrameDesc': 'Profilingiz uchun kumush ramka',
    'shop.colorTheme': 'Rangli tema',
    'shop.colorThemeDesc': 'Yorqin ranglar bilan dizayn',
    'shop.starBadge': 'Yulduz nishoni',
    'shop.starBadgeDesc': '100 ta topshiriq uchun',
    'shop.coinBoost': '3x Tanga Boost',
    'shop.coinBoostDesc': '12 soat davomida 3 barobar tanga',

    // AI Coach Screen
    'aiCoach.title': 'AI Murabbiy',
    'aiCoach.subtitle': 'Shaxsiy fitnes yordamchingiz',
    'aiCoach.greeting': 'Salom',
    'aiCoach.intro': 'Men YASHA - sizning shaxsiy sog\'lom hayot murabbiyingizman. Sizga qanday yordam bera olaman?',
    'aiCoach.placeholder': 'Savolingizni yozing...',
    'aiCoach.question1': 'Bugun nima yesam yaxshi?',
    'aiCoach.question2': 'Vazn yo\'qotish uchun maslahat',
    'aiCoach.question3': 'Uyqu sifatini yaxshilash',
    'aiCoach.error': 'Xatolik yuz berdi',
    'aiCoach.noStream': 'Stream mavjud emas',

    // Edit Profile Sheet
    'editProfile.title': 'Profilni tahrirlash',
    'editProfile.save': 'Saqlash',
    'editProfile.name': 'Ism',
    'editProfile.namePlaceholder': 'Ismingiz',
    'editProfile.phone': 'Telefon',
    'editProfile.age': 'Yosh',
    'editProfile.height': 'Bo\'y (sm)',
    'editProfile.weight': 'Vazn (kg)',
    'editProfile.saved': 'Profil yangilandi!',

    // Privacy Sheet
    'privacy.title': 'Maxfiylik',
    'privacy.dataSecurity': 'Ma\'lumotlar xavfsizligi',
    'privacy.dataSecurityDesc': 'Barcha ma\'lumotlaringiz qurilmangizda saqlanadi va hech qanday serverga yuborilmaydi.',
    'privacy.policy': 'Maxfiylik siyosati',
    'privacy.policyDesc': 'Biz foydalanuvchilarning shaxsiy ma\'lumotlarini uchinchi tomonlarga bermaimiz.',
    'privacy.encryption': 'Shifrlash',
    'privacy.encryptionDesc': 'To\'lov ma\'lumotlari xavfsiz shifrlangan holda saqlanadi.',
    'privacy.deleteData': 'Ma\'lumotlarni o\'chirish',
    'privacy.deleteDataDesc': 'Barcha shaxsiy ma\'lumotlaringizni va sozlamalaringizni o\'chirish',
    'privacy.deleteAll': 'Barcha ma\'lumotlarni o\'chirish',
    'privacy.confirmDelete': 'Barcha ma\'lumotlarni o\'chirmoqchimisiz? Bu amalni ortga qaytarib bo\'lmaydi.',
    'privacy.deleted': 'Ma\'lumotlar o\'chirildi. Ilova qayta yuklanmoqda...',

    // Help Sheet
    'help.title': 'Yordam',
    'help.support': 'Qo\'llab-quvvatlash',
    'help.supportDesc': 'Savollaringiz bormi? Telegram orqali biz bilan bog\'laning.',
    'help.contactTelegram': 'Telegram orqali yozish',
    'help.faq': 'Ko\'p so\'raladigan savollar',
    'help.faq1': 'Premium rejaning afzalliklari nimada?',
    'help.faq1Answer': 'Premium rejada siz 7 kunlik shaxsiy taomnoma, mashqlar rejasi, AI murabbiy bilan cheksiz muloqot va kaloriya tahlili imkoniyatlaridan foydalanishingiz mumkin.',
    'help.faq2': 'Suv ichish eslatmasi qanday ishlaydi?',
    'help.faq2Answer': 'Bildirishnomalar bo\'limida suv eslatmasini yoqsangiz, ilova har soatda sizga suv ichishni eslatib turadi.',
    'help.faq3': 'Mashqlar qanday tuzilgan?',
    'help.faq3Answer': 'Mashqlar sizning maqsadingiz va jismoniy tayyorgarligingizga qarab AI tomonidan shaxsiy tarzda tuziladi.',
    'help.faq4': 'Obuna qanday bekor qilinadi?',
    'help.faq4Answer': 'Obunani bekor qilish uchun Telegram botimizga yozing yoki /cancel buyrug\'ini yuboring.',
    'help.faq5': 'Ma\'lumotlarim xavfsizmi?',
    'help.faq5Answer': 'Ha, barcha ma\'lumotlaringiz faqat sizning qurilmangizda saqlanadi. Biz hech qanday shaxsiy ma\'lumotni serverlarimizda saqlamaymiz.',
    'help.copyright': '© 2024 YASHA. Barcha huquqlar himoyalangan.',

    // Notifications Sheet
    'notifications.title': 'Bildirishnomalar',
    'notifications.info': 'Bildirishnomalar sizga sog\'lom odatlarni eslatib turadi',
    'notifications.water': 'Suv eslatmasi',
    'notifications.waterDesc': 'Har soatda suv ichishni eslatadi',
    'notifications.workout': 'Mashq eslatmasi',
    'notifications.workoutDesc': 'Kundalik mashq vaqtini eslatadi',
    'notifications.sleep': 'Uyqu eslatmasi',
    'notifications.sleepDesc': 'Uxlash vaqtini eslatadi',
    'notifications.meal': 'Ovqat eslatmasi',
    'notifications.mealDesc': 'Ovqatlanish vaqtini eslatadi',
    'notifications.enabled': 'Bildirishnoma yoqildi',
    'notifications.disabled': 'Bildirishnoma o\'chirildi',

    // Paywall
    'paywall.close': 'Yopish',
    'paywall.hero': 'Premium rejaga o\'ting',
    'paywall.featureOnly': 'faqat premium uchun',
    'paywall.popular': 'MASHHUR',
    'paywall.perMonth': 'oyiga',
    'paywall.premiumDesc': 'Sog\'lom turmush tarzini tizimlashtirishni boshlaganlar uchun ideal tanlov',
    'paywall.vipDesc': 'Maksimal natija va to\'liq erkinlikni xohlovchilar uchun',
    'paywall.subscribe': 'Imkoniyatlarni kengaytirish',
    'paywall.telegramInfo': '💬 To\'lovni amalga oshirish uchun Telegram oynasi ochiladi',
    'paywall.trial': '7 kunlik bepul sinov • Istalgan vaqtda bekor qilish mumkin',
    'paywall.success': 'To\'lov muvaffaqiyatli amalga oshirildi! 🎉',
    'paywall.failed': 'To\'lov bekor qilindi yoki xatolik yuz berdi.',
    'paywall.error': 'To\'lov tizimiga ulanishda xatolik yuz berdi.',

    // Onboarding
    'onboarding.slogan': 'Sog\'lom hayot murabbiyi',
    'onboarding.welcome': 'Shaxsiy AI fitnes va dieta murabbiyi. Sog\'lom hayot yo\'lingizda biz bilan boring!',
    'onboarding.start': 'Boshlash',
    'onboarding.continue': 'Davom etish',
    'onboarding.skip': 'O\'tkazib yuborish',
    'onboarding.phoneTitle': 'Telefon raqamingiz',
    'onboarding.phoneDesc': 'Hisobingizni yaratish uchun telefon raqamingizni kiriting',
    'onboarding.phonePlaceholder': '+998 90 123 45 67',
    'onboarding.nameTitle': 'Sizni qanday chaqiramiz?',
    'onboarding.nameDesc': 'Ismingizni kiriting',
    'onboarding.namePlaceholder': 'Ismingiz',
    'onboarding.bodyTitle': 'Jismoniy ko\'rsatkichlar',
    'onboarding.bodyDesc': 'Sizga mos rejani tuzish uchun kerak',
    'onboarding.male': 'Erkak',
    'onboarding.female': 'Ayol',
    'onboarding.age': 'Yosh',
    'onboarding.ageSuffix': 'yosh',
    'onboarding.height': 'Bo\'y',
    'onboarding.heightSuffix': 'sm',
    'onboarding.weight': 'Vazn',
    'onboarding.weightSuffix': 'kg',
    'onboarding.goalTitle': 'Maqsadingiz nima?',
    'onboarding.goalDesc': 'Asosiy maqsadingizni tanlang',
    'onboarding.goalLose': 'Vazn yo\'qotish',
    'onboarding.goalLoseDesc': 'Ortiqcha kilolardan xalos bo\'lish',
    'onboarding.goalGain': 'Vazn olish',
    'onboarding.goalGainDesc': 'Mushak massasini oshirish',
    'onboarding.goalMaintain': 'Sog\'lom turmush',
    'onboarding.goalMaintainDesc': 'Hozirgi vazningizni saqlash',
    'onboarding.activityTitle': 'Faollik darajangiz',
    'onboarding.activityDesc': 'Kundalik faolligingizni tanlang',
    'onboarding.activitySedentary': 'Kam harakatli',
    'onboarding.activitySedentaryDesc': 'Ofis ishi, kam yurish',
    'onboarding.activityLight': 'Engil faol',
    'onboarding.activityLightDesc': 'Kunlik 30 daqiqa yurish',
    'onboarding.activityModerate': 'O\'rtacha faol',
    'onboarding.activityModerateDesc': 'Haftada 3-4 marta sport',
    'onboarding.activityActive': 'Faol',
    'onboarding.activityActiveDesc': 'Har kuni sport mashqlari',
    'onboarding.activityVeryActive': 'Juda faol',
    'onboarding.activityVeryActiveDesc': 'Intensiv mashqlar har kuni',
    'onboarding.allergyTitle': 'Allergiyalaringiz bormi?',
    'onboarding.allergyDesc': 'Tanlang yoki o\'tkazib yuboring',
    'onboarding.allergyDairy': 'Sut mahsulotlari',
    'onboarding.allergyNuts': 'Yong\'oq',
    'onboarding.allergyEggs': 'Tuxum',
    'onboarding.allergyGluten': 'Gluten',
    'onboarding.allergySeafood': 'Dengiz mahsulotlari',
    'onboarding.allergySoy': 'Soya',
    'onboarding.completeTitle': 'Tabriklaymiz! 🎉',
    'onboarding.completeDesc': 'Sizning shaxsiy rejangiz tayyor. 7 kunlik bepul sinov davri boshlandi!',
    'onboarding.letsStart': 'Boshlaymiz!',
  },
  ru: {
    // Common
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.done': 'Готово',
    'common.add': 'Добавить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'common.today': 'Сегодня',
    'common.days': 'дн.',
    'common.hours': 'ч.',
    'common.minutes': 'мин.',
    'common.all': 'Все',
    'common.day': 'День',

    // Days of week
    'day.mon': 'Пн',
    'day.tue': 'Вт',
    'day.wed': 'Ср',
    'day.thu': 'Чт',
    'day.fri': 'Пт',
    'day.sat': 'Сб',
    'day.sun': 'Вс',

    // Navigation
    'nav.home': 'Главная',
    'nav.explore': 'Ещё',
    'nav.menu': 'Еда',
    'nav.workout': 'Тренировка',
    'nav.profile': 'Профиль',

    // Home Screen
    'home.greeting': 'Привет',
    'home.howAreYou': 'Как настроение сегодня?',
    'home.todayResults': 'Результаты за сегодня',
    'home.streaks': 'Серии',
    'home.aiCoach': 'AI Тренер',
    'home.personalAdvice': 'Персональные советы',
    'home.dailyHabits': 'Ежедневные привычки',
    'home.waterSleepSteps': 'Вода, сон, шаги',
    'home.exploreMore': 'Ещё больше',
    'home.friendsCompetition': 'Друзья, соревнования, магазин',
    'home.trialPeriod': 'Пробный период',
    'home.daysRemaining': 'дней осталось',
    'home.user': 'Пользователь',

    // Stats
    'stats.water': 'Вода',
    'stats.calories': 'Калории',
    'stats.sleep': 'Сон',
    'stats.workout': 'Тренировка',
    'stats.steps': 'Шаги',
    'stats.mood': 'Настроение',
    'stats.completed': 'Выполнено',
    'stats.pending': 'Ожидается',

    // Menu Screen
    'menu.title': 'Ежедневное меню',
    'menu.weekly': '7 дней',
    'menu.dailyTotal': 'Калории за день',
    'menu.consumed': 'потреблено',
    'menu.recommended': 'рекомендовано',
    'menu.remaining': 'осталось',
    'menu.excess': 'лишнее',
    'menu.actual': 'Реальные',
    'menu.actualData': 'Реальные данные',
    'menu.breakfast': 'Завтрак',
    'menu.lunch': 'Обед',
    'menu.dinner': 'Ужин',
    'menu.snack': 'Перекус',
    'menu.tip': 'Совет',
    'menu.tipText': 'Пейте минимум 2 литра воды в день и соблюдайте интервал 3-4 часа между приёмами пищи.',
    'menu.premiumInfo': 'В бесплатной версии доступно только сегодняшнее меню. Для AI меню нужен Premium.',
    'menu.protein': 'белок',
    'menu.carbs': 'углеводы',
    'menu.fat': 'жиры',
    'menu.iAteIt': 'Я это съел',
    'menu.mealAddedSuccess': 'Блюдо добавлено в дневник!',

    // Workout Screen
    'workout.title': 'Тренировки',
    'workout.videoWorkouts': 'Видео тренировки',
    'workout.comingSoon': 'Скоро',
    'workout.videosSoon': 'Видео тренировки скоро появятся',
    'workout.warmupTip': 'Перед каждой тренировкой делайте 5 минут разминки. Это предотвратит травмы.',
    'workout.premiumInfo': 'В бесплатной версии 3 базовых тренировки. Для AI программы нужен Premium.',
    'workout.homeBasic': 'Домашняя тренировка - Начальный',
    'workout.cardioStretching': 'Кардио и растяжка',
    'workout.upperBody': 'Верхняя часть тела',
    'workout.homeCardio': 'Домашнее кардио',
    'workout.abs': 'Мышцы пресса',
    'workout.fullBody': 'Тренировка всего тела',

    // Habits Screen
    'habits.title': 'Ежедневные привычки',
    'habits.subtitle': 'Следите за здоровыми привычками',
    'habits.waterIntake': 'Потребление воды',
    'habits.steps': 'Шаги',
    'habits.sleep': 'Сон',
    'habits.dailyTip': 'Совет дня',
    'habits.dailyTipText': 'Пейте стакан воды каждый час. Это ускоряет метаболизм и даёт энергию!',
    'habits.todayMood': 'Настроение сегодня',
    'habits.moodBad': 'Плохое',
    'habits.moodOk': 'Нормальное',
    'habits.moodGood': 'Отличное',
    'habits.waterAdded': '+250 мл воды добавлено!',
    'habits.stepsAdded': 'шагов добавлено!',
    'habits.sleepSaved': 'часов сна сохранено!',
    'habits.badMoodMsg1': 'Всё наладится! Уделите сегодня больше внимания себе.',
    'habits.badMoodMsg2': 'Трудные дни проходят. Вы сильны!',
    'habits.badMoodMsg3': 'Каждый день - новая возможность. Завтра будет лучше!',
    'habits.goodMoodMsg': 'Отлично! Сегодня хороший день!',

    // Profile Screen
    'profile.title': 'Профиль',
    'profile.personalInfo': 'Личная информация',
    'profile.age': 'Возраст',
    'profile.height': 'Рост',
    'profile.weight': 'Вес',
    'profile.goal': 'Цель',
    'profile.settings': 'Настройки',
    'profile.settingsLang': 'Настройки и язык',
    'profile.notifications': 'Уведомления',
    'profile.language': 'Язык',
    'profile.theme': 'Тема',
    'profile.privacy': 'Конфиденциальность',
    'profile.help': 'Помощь',
    'profile.editProfile': 'Редактировать профиль',
    'profile.logout': 'Выйти',

    // Calories Screen
    'calories.title': 'Калории',
    'calories.dailyJournal': 'Дневник питания',
    'calories.addMeal': 'Добавить приём пищи',
    'calories.todayCalories': 'Калории сегодня',
    'calories.remaining': 'Осталось',
    'calories.protein': 'Белок',
    'calories.carbs': 'Углеводы',
    'calories.fat': 'Жиры',
    'calories.todayMeals': 'Приёмы пищи сегодня',
    'calories.noMeals': 'Ещё нет приёмов пищи',
    'calories.addMealHint': 'Нажмите + чтобы добавить',
    'calories.mealName': 'Название блюда',
    'calories.mealType': 'Тип приёма пищи',
    'calories.mealAdded': 'Добавлено!',
    'calories.mealDeleted': 'Удалено',
    'calories.mealDeletedDesc': 'Приём пищи удалён',
    'calories.requiredFields': 'Название и калории обязательны',
    'calories.gazak': 'Перекус',

    // Recipes Screen
    'recipes.title': 'Рецепты',
    'recipes.subtitle': 'Здоровые блюда',
    'recipes.ingredients': 'Ингредиенты',
    'recipes.preparation': 'Приготовление',
    'recipes.kcal': 'ккал',
    'recipes.time': 'время',
    'recipes.servings': 'порций',

    // Daily Tasks
    'tasks.title': 'Ежедневные задания',
    'tasks.completed': 'выполнено',
    'tasks.yourLevel': 'Ваш уровень',
    'tasks.level': 'Уровень',
    'tasks.next': 'Следующий',
    'tasks.points': 'очков',
    'tasks.allCompleted': 'Все задания выполнены!',
    'tasks.greatJob': 'Отличная работа!',
    'tasks.bonus': 'бонус',
    'tasks.todayTasks': 'Задания на сегодня',
    'tasks.claimReward': 'Получить награду',
    'tasks.rewardClaimed': 'Награда получена',
    'tasks.rewardReceived': 'Награда получена!',
    'tasks.progress': 'Прогресс',
    'tasks.drinkWater': 'Выпить 2.5л воды',
    'tasks.drinkWaterDesc': 'Достигните дневной цели по воде',
    'tasks.walk10k': '10,000 шагов',
    'tasks.walk10kDesc': 'Пройдите 10 тысяч шагов сегодня',
    'tasks.doWorkout': 'Сделать тренировку',
    'tasks.doWorkoutDesc': 'Выполните хотя бы одну тренировку',
    'tasks.sleep8h': 'Спать 8 часов',
    'tasks.sleep8hDesc': 'Получите качественный сон',
    'tasks.eat3meals': '3 приёма пищи',
    'tasks.eat3mealsDesc': 'Съешьте три здоровых приёма пищи',

    // Settings
    'settings.title': 'Настройки',
    'settings.language': 'Язык',
    'settings.uzbek': 'Узбекский',
    'settings.russian': 'Русский',
    'settings.theme': 'Тема',
    'settings.dark': 'Тёмная',
    'settings.light': 'Светлая',
    'settings.system': 'Системная',

    // Paywall
    'paywall.title': 'Нужен Premium',
    'paywall.feature': 'Для этой функции нужен Premium',
    'paywall.upgrade': 'Расширить возможности',
    'paywall.later': 'Позже',
    'paywall.aiMenu': 'AI план меню',
    'paywall.aiWorkout': 'AI программа тренировок',

    // Explore Screen
    'explore.title': 'Ещё больше',
    'explore.subtitle': 'Все функции в одном месте',
    'explore.tracking': 'Отслеживание',
    'explore.wellness': 'Здоровье',
    'explore.social': 'Социальное',
    'explore.rewards': 'Награды',
    'explore.weight': 'Вес',
    'explore.weightDesc': 'История веса',
    'explore.calories': 'Калории',
    'explore.caloriesDesc': 'Дневной учёт',
    'explore.tasks': 'Задания',
    'explore.tasksDesc': 'Ежедневные дела',
    'explore.reports': 'Отчёты',
    'explore.reportsDesc': 'Статистика',
    'explore.workouts': 'Тренировки',
    'explore.workoutsDesc': 'Видео уроки',
    'explore.meditation': 'Медитация',
    'explore.meditationDesc': 'Расслабление',
    'explore.recipes': 'Рецепты',
    'explore.recipesDesc': 'Здоровая еда',
    'explore.friends': 'Друзья',
    'explore.friendsDesc': 'Рейтинги',
    'explore.challenges': 'Соревнования',
    'explore.challengesDesc': 'Состязания',
    'explore.achievements': 'Достижения',
    'explore.achievementsDesc': 'Медали',
    'explore.shop': 'Магазин',
    'explore.shopDesc': 'Подарки',

    // Weight Screen
    'weight.title': 'Вес',
    'weight.subtitle': 'Отслеживайте свой вес',
    'weight.current': 'Текущий вес',
    'weight.change': 'Изменение',
    'weight.goal': 'Цель',
    'weight.last14days': 'Последние 14 дней',
    'weight.history': 'История',
    'weight.saved': 'Вес сохранён!',
    'weight.invalidWeight': 'Введите корректный вес (30-300 кг)',
    'weight.placeholder': 'Вес (кг)',

    // Reports Screen
    'reports.title': 'Отчёты',
    'reports.subtitle': 'Недельная статистика',
    'reports.totalWater': 'Всего воды',
    'reports.totalSteps': 'Всего шагов',
    'reports.avgSleep': 'Средний сон',
    'reports.goalDays': 'Дней цели',
    'reports.waterChart': 'Вода (100мл)',
    'reports.stepsChart': 'Шаги (тыс.)',
    'reports.weeklyAnalysis': 'Недельный анализ',
    'reports.great': 'Отлично! Вы достигаете своих целей. Продолжайте!',
    'reports.good': 'Хорошо! Ещё немного усилий и достигнете цели!',
    'reports.start': 'Каждый день важен. Начните с маленьких шагов!',

    // Workout Library Screen
    'workoutLib.title': 'Тренировки',
    'workoutLib.subtitle': 'Видео библиотека и таймер',
    'workoutLib.all': 'Все',
    'workoutLib.hiit': 'HIIT',
    'workoutLib.strength': 'Сила',
    'workoutLib.yoga': 'Йога',
    'workoutLib.cardio': 'Кардио',
    'workoutLib.flexibility': 'Гибкость',
    'workoutLib.beginner': 'Начальный',
    'workoutLib.intermediate': 'Средний',
    'workoutLib.advanced': 'Продвинутый',
    'workoutLib.min': 'мин',
    'workoutLib.recommendation': 'Рекомендация',
    'workoutLib.calorie': 'Калории',
    'workoutLib.completed': 'Тренировка завершена!',
    'workoutLib.caloriesBurned': 'ккал сожжено',
    'workoutLib.morningStretch': 'Утренняя растяжка',
    'workoutLib.morningStretchDesc': 'Пробуждение тела в начале дня',
    'workoutLib.hiitCardio': 'HIIT Кардио',
    'workoutLib.hiitCardioDesc': 'Высокоинтенсивная интервальная тренировка',
    'workoutLib.strengthTraining': 'Силовые упражнения',
    'workoutLib.strengthTrainingDesc': 'Силовые упражнения для всего тела',
    'workoutLib.yogaBasics': 'Основы йоги',
    'workoutLib.yogaBasicsDesc': 'Йога для начинающих',
    'workoutLib.absWorkout': 'Пресс',
    'workoutLib.absWorkoutDesc': 'Упражнения для мышц пресса',
    'workoutLib.tabata': 'Табата',
    'workoutLib.tabataDesc': '4-минутная интенсивная тренировка',

    // Meditation Screen
    'meditation.title': 'Медитация',
    'meditation.subtitle': 'Дыхательные упражнения',
    'meditation.relaxing': 'Расслабление',
    'meditation.relaxingDesc': 'Техника дыхания 4-7-8',
    'meditation.energizing': 'Энергия',
    'meditation.energizingDesc': 'Быстрое дыхание',
    'meditation.calm': 'Спокойствие',
    'meditation.calmDesc': 'Глубокое дыхание',
    'meditation.inhale': 'Вдохните',
    'meditation.hold': 'Задержите',
    'meditation.exhale': 'Выдохните',
    'meditation.rest': 'Отдохните',
    'meditation.cycles': 'Циклы',
    'meditation.tip': 'Совет',
    'meditation.relaxingTip': 'Используйте перед сном. Снижает стресс.',
    'meditation.energizingTip': 'Используйте утром или при усталости. Даёт энергию.',
    'meditation.calmTip': 'Используйте в любое время для снижения стресса.',

    // Friends Screen
    'friends.title': 'Друзья',
    'friends.subtitle': 'Соревнуйтесь и побеждайте!',
    'friends.search': 'Поиск пользователя...',
    'friends.friendsTab': 'Друзья',
    'friends.leaderboard': 'Рейтинг',
    'friends.online': 'Онлайн',
    'friends.offline': 'Офлайн',
    'friends.challenge': 'Вызов',
    'friends.requestSent': 'Запрос отправлен',
    'friends.requestSentDesc': 'отправлен запрос на дружбу',
    'friends.challengeSent': 'Вызов отправлен!',
    'friends.challengeSentDesc': 'отправлен вызов',
    'friends.enterUsername': 'Пожалуйста, введите имя пользователя',
    'friends.you': 'Вы',

    // Challenges Screen
    'challenges.title': 'Соревнования',
    'challenges.subtitle': 'Соревнуйтесь и побеждайте!',
    'challenges.active': 'Активные соревнования',
    'challenges.new': 'Новое соревнование',
    'challenges.name': 'Название',
    'challenges.type': 'Тип',
    'challenges.targetValue': 'Целевое значение',
    'challenges.duration': 'Длительность',
    'challenges.create': 'Создать',
    'challenges.join': 'Присоединиться',
    'challenges.progress': 'Прогресс',
    'challenges.participants': 'участников',
    'challenges.daysLeft': 'дней осталось',
    'challenges.steps': 'Шаги',
    'challenges.water': 'Вода',
    'challenges.workouts': 'Тренировки',
    'challenges.weight': 'Вес',
    'challenges.step': 'шагов',
    'challenges.workout': 'тренировок',
    'challenges.created': 'Соревнование создано!',
    'challenges.createdDesc': 'соревнование успешно создано',
    'challenges.joined': 'Вы присоединились!',
    'challenges.joinedDesc': 'вы присоединились к соревнованию',
    'challenges.fillAll': 'Заполните все поля',
    'challenges.3days': '3 дня',
    'challenges.7days': '7 дней',
    'challenges.14days': '14 дней',
    'challenges.30days': '30 дней',

    // Achievements Screen
    'achievements.title': 'Достижения',
    'achievements.subtitle': 'Значки и награды',
    'achievements.badges': 'Значки',
    'achievements.points': 'Очки',
    'achievements.waterStarter': 'Водохлёб',
    'achievements.waterStarterDesc': 'Первый день достиг цели по воде',
    'achievements.waterMaster': 'Мастер воды',
    'achievements.waterMasterDesc': '7 дней подряд достигал цели по воде',
    'achievements.stepCounter': 'Шагомер',
    'achievements.stepCounterDesc': 'Достиг 10,000 шагов',
    'achievements.sleepMaster': 'Мастер сна',
    'achievements.sleepMasterDesc': '7 дней спал по 8 часов',
    'achievements.fireStreak': 'Огненная серия',
    'achievements.fireStreakDesc': 'Достиг 14-дневной серии',
    'achievements.starCollector': 'Собиратель звёзд',
    'achievements.starCollectorDesc': 'Набрал 100 очков',
    'achievements.goldenCup': 'Золотой кубок',
    'achievements.goldenCupDesc': 'Набрал 500 очков',
    'achievements.perfectDay': 'Идеальный день',
    'achievements.perfectDayDesc': 'Достиг всех дневных целей',
    'achievements.1dayWater': '1 день воды',
    'achievements.7dayStreak': '7 дней серия',
    'achievements.10kSteps': '10,000 шагов',
    'achievements.14daysStreak': '14 дней подряд',
    'achievements.100points': '100 очков',
    'achievements.500points': '500 очков',
    'achievements.allGoals': 'Вода, сон, шаги',

    // Shop Screen
    'shop.title': 'Магазин',
    'shop.subtitle': 'Тратьте свои монеты',
    'shop.all': 'Все',
    'shop.frames': 'Рамки',
    'shop.themes': 'Темы',
    'shop.boosts': 'Бусты',
    'shop.owned': 'Есть',
    'shop.buy': 'Купить',
    'shop.alreadyOwned': 'Уже куплено',
    'shop.alreadyOwnedDesc': 'Этот товар у вас уже есть',
    'shop.notEnough': 'Недостаточно монет',
    'shop.notEnoughDesc': 'Для этого товара нужно монет',
    'shop.success': 'Покупка успешна!',
    'shop.purchased': 'куплено',
    'shop.goldenFrame': 'Золотая рамка',
    'shop.goldenFrameDesc': 'Золотая рамка для профиля',
    'shop.darkTheme': 'Тёмная тема',
    'shop.darkThemeDesc': 'Специальный тёмный дизайн',
    'shop.xpBoost': '2x XP Буст',
    'shop.xpBoostDesc': '2x XP на 24 часа',
    'shop.championBadge': 'Значок чемпиона',
    'shop.championBadgeDesc': 'Специальный значок чемпиона',
    'shop.silverFrame': 'Серебряная рамка',
    'shop.silverFrameDesc': 'Серебряная рамка для профиля',
    'shop.colorTheme': 'Цветная тема',
    'shop.colorThemeDesc': 'Дизайн с яркими цветами',
    'shop.starBadge': 'Значок звезды',
    'shop.starBadgeDesc': 'За 100 выполненных заданий',
    'shop.coinBoost': '3x Монет Буст',
    'shop.coinBoostDesc': '3x монет на 12 часов',

    // AI Coach Screen
    'aiCoach.title': 'AI Тренер',
    'aiCoach.subtitle': 'Ваш персональный фитнес-помощник',
    'aiCoach.greeting': 'Привет',
    'aiCoach.intro': 'Я YASHA - ваш персональный тренер здорового образа жизни. Чем могу помочь?',
    'aiCoach.placeholder': 'Напишите ваш вопрос...',
    'aiCoach.question1': 'Что поесть сегодня?',
    'aiCoach.question2': 'Советы по снижению веса',
    'aiCoach.question3': 'Улучшить качество сна',
    'aiCoach.error': 'Произошла ошибка',
    'aiCoach.noStream': 'Поток недоступен',

    // Edit Profile Sheet
    'editProfile.title': 'Редактировать профиль',
    'editProfile.save': 'Сохранить',
    'editProfile.name': 'Имя',
    'editProfile.namePlaceholder': 'Ваше имя',
    'editProfile.phone': 'Телефон',
    'editProfile.age': 'Возраст',
    'editProfile.height': 'Рост (см)',
    'editProfile.weight': 'Вес (кг)',
    'editProfile.saved': 'Профиль обновлён!',

    // Privacy Sheet
    'privacy.title': 'Конфиденциальность',
    'privacy.dataSecurity': 'Безопасность данных',
    'privacy.dataSecurityDesc': 'Все ваши данные хранятся на вашем устройстве и не отправляются на сервер.',
    'privacy.policy': 'Политика конфиденциальности',
    'privacy.policyDesc': 'Мы не передаём личные данные пользователей третьим лицам.',
    'privacy.encryption': 'Шифрование',
    'privacy.encryptionDesc': 'Платёжные данные хранятся в зашифрованном виде.',
    'privacy.deleteData': 'Удалить данные',
    'privacy.deleteDataDesc': 'Удалить все ваши личные данные и настройки',
    'privacy.deleteAll': 'Удалить все данные',
    'privacy.confirmDelete': 'Вы хотите удалить все данные? Это действие нельзя отменить.',
    'privacy.deleted': 'Данные удалены. Приложение перезагружается...',

    // Help Sheet
    'help.title': 'Помощь',
    'help.support': 'Поддержка',
    'help.supportDesc': 'Есть вопросы? Свяжитесь с нами через Telegram.',
    'help.contactTelegram': 'Написать в Telegram',
    'help.faq': 'Часто задаваемые вопросы',
    'help.faq1': 'В чём преимущества Premium?',
    'help.faq1Answer': 'В Premium вы получаете 7-дневное персональное меню, план тренировок, неограниченное общение с AI тренером и анализ калорий.',
    'help.faq2': 'Как работает напоминание о воде?',
    'help.faq2Answer': 'Включите напоминание о воде в разделе уведомлений, и приложение будет напоминать вам пить воду каждый час.',
    'help.faq3': 'Как составлены тренировки?',
    'help.faq3Answer': 'Тренировки составляются AI персонально под вашу цель и физическую подготовку.',
    'help.faq4': 'Как отменить подписку?',
    'help.faq4Answer': 'Для отмены подписки напишите в наш Telegram бот или отправьте команду /cancel.',
    'help.faq5': 'Мои данные в безопасности?',
    'help.faq5Answer': 'Да, все ваши данные хранятся только на вашем устройстве. Мы не храним личные данные на наших серверах.',
    'help.copyright': '© 2024 YASHA. Все права защищены.',

    // Notifications Sheet
    'notifications.title': 'Уведомления',
    'notifications.info': 'Уведомления напоминают вам о здоровых привычках',
    'notifications.water': 'Напоминание о воде',
    'notifications.waterDesc': 'Напоминает пить воду каждый час',
    'notifications.workout': 'Напоминание о тренировке',
    'notifications.workoutDesc': 'Напоминает о времени тренировки',
    'notifications.sleep': 'Напоминание о сне',
    'notifications.sleepDesc': 'Напоминает о времени сна',
    'notifications.meal': 'Напоминание о еде',
    'notifications.mealDesc': 'Напоминает о времени приёма пищи',
    'notifications.enabled': 'Уведомление включено',
    'notifications.disabled': 'Уведомление выключено',

    // Paywall
    'paywall.close': 'Закрыть',
    'paywall.hero': 'Перейти на Premium',
    'paywall.featureOnly': 'только для premium',
    'paywall.popular': 'ПОПУЛЯРНЫЙ',
    'paywall.perMonth': 'в месяц',
    'paywall.premiumDesc': 'Идеальный выбор для тех, кто начинает систематизировать здоровый образ жизни',
    'paywall.vipDesc': 'Для тех, кто хочет максимальных результатов и полной свободы',
    'paywall.subscribe': 'Расширить возможности',
    'paywall.telegramInfo': '💬 Для оплаты откроется окно Telegram',
    'paywall.trial': '7 дней бесплатно • Можно отменить в любое время',
    'paywall.success': 'Оплата прошла успешно! 🎉',
    'paywall.failed': 'Оплата отменена или произошла ошибка.',
    'paywall.error': 'Ошибка при подключении к платежной системе.',

    // Onboarding
    'onboarding.slogan': 'Тренер здорового образа жизни',
    'onboarding.welcome': 'Персональный AI фитнес и диетический тренер. Идите к здоровой жизни вместе с нами!',
    'onboarding.start': 'Начать',
    'onboarding.continue': 'Продолжить',
    'onboarding.skip': 'Пропустить',
    'onboarding.phoneTitle': 'Ваш номер телефона',
    'onboarding.phoneDesc': 'Введите номер телефона для создания аккаунта',
    'onboarding.phonePlaceholder': '+998 90 123 45 67',
    'onboarding.nameTitle': 'Как вас зовут?',
    'onboarding.nameDesc': 'Введите ваше имя',
    'onboarding.namePlaceholder': 'Ваше имя',
    'onboarding.bodyTitle': 'Физические показатели',
    'onboarding.bodyDesc': 'Нужно для составления подходящего плана',
    'onboarding.male': 'Мужчина',
    'onboarding.female': 'Женщина',
    'onboarding.age': 'Возраст',
    'onboarding.ageSuffix': 'лет',
    'onboarding.height': 'Рост',
    'onboarding.heightSuffix': 'см',
    'onboarding.weight': 'Вес',
    'onboarding.weightSuffix': 'кг',
    'onboarding.goalTitle': 'Какова ваша цель?',
    'onboarding.goalDesc': 'Выберите основную цель',
    'onboarding.goalLose': 'Похудеть',
    'onboarding.goalLoseDesc': 'Избавиться от лишних килограммов',
    'onboarding.goalGain': 'Набрать вес',
    'onboarding.goalGainDesc': 'Увеличить мышечную массу',
    'onboarding.goalMaintain': 'Здоровый образ жизни',
    'onboarding.goalMaintainDesc': 'Поддерживать текущий вес',
    'onboarding.activityTitle': 'Уровень активности',
    'onboarding.activityDesc': 'Выберите вашу ежедневную активность',
    'onboarding.activitySedentary': 'Малоподвижный',
    'onboarding.activitySedentaryDesc': 'Офисная работа, мало ходьбы',
    'onboarding.activityLight': 'Легко активный',
    'onboarding.activityLightDesc': '30 минут ходьбы в день',
    'onboarding.activityModerate': 'Умеренно активный',
    'onboarding.activityModerateDesc': 'Спорт 3-4 раза в неделю',
    'onboarding.activityActive': 'Активный',
    'onboarding.activityActiveDesc': 'Ежедневные тренировки',
    'onboarding.activityVeryActive': 'Очень активный',
    'onboarding.activityVeryActiveDesc': 'Интенсивные тренировки каждый день',
    'onboarding.allergyTitle': 'Есть ли у вас аллергии?',
    'onboarding.allergyDesc': 'Выберите или пропустите',
    'onboarding.allergyDairy': 'Молочные продукты',
    'onboarding.allergyNuts': 'Орехи',
    'onboarding.allergyEggs': 'Яйца',
    'onboarding.allergyGluten': 'Глютен',
    'onboarding.allergySeafood': 'Морепродукты',
    'onboarding.allergySoy': 'Соя',
    'onboarding.completeTitle': 'Поздравляем! 🎉',
    'onboarding.completeDesc': 'Ваш персональный план готов. Начался 7-дневный бесплатный период!',
    'onboarding.letsStart': 'Начнём!',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { language: userLanguage, updateLanguage } = useUser();
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('yasha_language');
    return (saved as Language) || userLanguage || 'uz';
  });

  // Sync with UserContext when it changes (e.g. from backend)
  useEffect(() => {
    if (userLanguage && userLanguage !== language) {
      setLanguageState(userLanguage as Language);
      localStorage.setItem('yasha_language', userLanguage);
    }
  }, [userLanguage, language]);

  const setLanguage = useCallback((lang: Language) => {
    localStorage.setItem('yasha_language', lang);
    setLanguageState(lang);
    if (updateLanguage) {
      updateLanguage(lang);
    }
  }, [updateLanguage]);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
