# Localization dictionary
TRANS = {
    "uz": {
        "select_language": "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык / 🇬🇧 Select language",
        "language_selected": "✅ O'zbek tili tanlandi.",
        "welcome": "Assalomu alaykum, {name}! YASHA Fitness Botiga xush kelibsiz.",
        "enter_name": "Ismingizni kiriting:",
        "enter_age": "Yoshingizni kiriting (faqat raqam):",
        "enter_gender": "Jinsingizni tanlang:",
        "male": "Erkak 👨",
        "female": "Ayol 👩",
        "enter_height": "Bo'yingizni kiriting (sm):",
        "enter_weight": "Vazningizni kiriting (kg):",
        "enter_goal": "Maqsadingizni tanlang:",
        "goal_weight_loss": "Ozish 📉",
        "goal_mass_gain": "Massa olish 💪",
        "goal_health": "Sog'lom bo'lish ❤️",
        "allergy_question": "Sizda biron mahsulotga allergiya bormi?",
        "yes": "Ha",
        "no": "Yo'q",
        "enter_allergy": "Qaysi mahsulotlarga allergiyangiz bor? Yozib yuboring:",
        "calculating": "⏳ Ma'lumotlaringiz tahlil qilinmoqda...",
        "onboarding_complete": "✅ Tabriklaymiz! Siz ro'yxatdan o'tdingiz.",
        
        # Main Menu
        "menu_plan": "📅 Mening rejam",
        "menu_profile": "👤 Profil",
        "menu_premium": "💎 Premium",
        "menu_progress": "📈 Natijalarim",
        "menu_feedback": "✍️ Fikr bildirish",
        "menu_settings": "⚙️ Sozlamalar",
        
        # Profile
        "profile_title": "👤 **Sizning Profilingiz**",
        "name": "Ism",
        "age": "Yosh",
        "gender": "Jins",
        "height": "Bo'y",
        "weight": "Vazn",
        "goal": "Maqsad",
        "allergies": "Allergiya",
        "status": "Status",
        "premium": "Premium",
        "free": "Bepul",
        "edit_profile": "✏️ Tahrirlash",
        "back": "Ortga",
        
        # Premium
        "premium_title": "💎 **Premium Obuna**",
        "premium_desc": "Premium obuna bilan siz quyidagilarga ega bo'lasiz:\n\n✅ Individual AI mashq rejasi\n✅ Individual AI ovqatlanish rejasi\n✅ Cheklovsiz so'rovlar\n✅ Tezkor yordam",
        "buy_1_month": "1 oy - 50,000 so'm",
        "buy_3_months": "3 oy - 120,000 so'm",
        "payment_success": "To'lov muvaffaqiyatli amalga oshirildi! Sizga Premium obuna berildi.",
        
        # Workout
        "btn_workout": "🏋️‍♂️ Mashqlar rejasi",
        "btn_meal": "🍏 Ovqatlanish rejasi",
        "choose_plan_type": "Qaysi reja kerak?",
        "generating_plan": "⏳ AI reja tuzmoqda...",
        
        # Errors
        "error_generic": "❌ Xatolik yuz berdi.",
        "error_number": "❌ Iltimos, raqam kiriting.",
        "enter_phone": "Telefon raqamingizni yuboring:",
        "invalid_phone_format": "❌ Iltimos, telefon raqamingizni kontakt sifatida yuboring 👇\n\nPastdagi tugmani bosing:",
        "name_cannot_be_empty": "❌ Ism bo'sh bo'lishi mumkin emas.",
        "enter_age_error": "Iltimos, yoshingizni raqamda kiriting:",
        "enter_age_range_error": "Yoshingizni to'g'ri kiriting (10-120 oralig'ida):",
        "old_button": "Eski tugma.",
        "enter_height_error": "Iltimos, bo'yingizni raqamda kiriting (sm):",
        "enter_height_range_error": "Bo'yingizni to'g'ri kiriting (50-250 sm):",
        "enter_weight_error": "Vazningizni to'g'ri kiriting (20-300 kg):",
        "choose_activity": "Jismoniy faollik darajangizni tanlang:",
        "choose_goal": "Maqsadingizni tanlang:",
        "allergy_details_prompt": "📝 Qanday hastalik yoki nima mahsulotlarga allergiyangiz bor?\n\nMasalan: yong'oq, sut, tuxum, gluten, dengiz mahsulotlari",
        
        # Activity Levels
        "activity_sedentary": "Kam harakat 🪑",
        "activity_light": "Yengil faol 🚶‍♂️",
        "activity_moderate": "O'rtacha faol 🏃‍♂️",
        "activity_active": "Juda faol 🏋️‍♂️",
        "activity_athlete": "Atlet 🔥",
        
        # Main Menu Buttons
        "btn_calorie": "🍽 Kaloriya tahlili",
        "btn_habits": "🔁 Odatlar",
        "btn_trainer": "🎯 Shaxsiy Murabbiy",
        "btn_challenges": "🔥 Chellenjlar",
        "btn_premium": "💎 Premium",
        "btn_profile": "👤 Profil",
        "btn_referral": "🔗 Referal",
        "btn_feedback": "📩 Qayta aloqa",
        
        # Other Buttons
        "btn_ai_workout": "🤖 AI mashg‘ulot rejasi",
        "btn_ai_meal": "🥦 AI ovqatlanish rejasi",
        "btn_calorie_premium": "🍽 Kaloriya tahlili (premium)",
        "btn_water": "💧 Suv ichish",
        "btn_sleep": "😴 Uyqu",
        "btn_mood": "🙂 Kayfiyat",
        "btn_steps": "🚶 Qadamlar",
        "btn_habit_stats": "📊 Odatlar statistikasi",
        "btn_ai_qa": "❓ AI savol-javob",
        "btn_ai_recipe": "🍳 AI retsept",
        "btn_ai_shopping": "🛒 AI shopping list",
        "btn_points": "📊 Ballarim",
        "btn_rewards": "🎁 Mukofotlar",
        "btn_rules": "📜 Qoidalar",
        "btn_back_premium": "⬅️ Premium menyu",
        "btn_weekly_challenge": "📆 Haftalik challenge",
        "btn_monthly_challenge": "🗓 Oylik challenge",
        "btn_friends_challenge": "👥 Do‘stlar challenge",
        "btn_leaderboard": "🏆 Leaderboard",
        "btn_edit_profile": "✏️ Ma’lumotlarni tahrirlash",
        "btn_health_stats": "📊 Sog‘liq statistikasi",
        "btn_change_goal": "🎯 Maqsadni o‘zgartirish",
        "btn_buy_premium": "💳 Premium sotib olish",
        "btn_tariffs": "ℹ️ Tariflar",
        "btn_coins": "🟡 Yasha Coin",
        "btn_workout_done": "Mashq qildim ✅",
        "btn_water_done": "Suv ichdim 💧",
        "btn_phone_request": "📱 Telefon raqamni yuborish",
    },
    "ru": {
        "select_language": "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык / 🇬🇧 Select language",
        "language_selected": "✅ Выбран Русский язык.",
        "welcome": "Здравствуйте, {name}! Добро пожаловать в YASHA Fitness Bot.",
        "enter_name": "Введите ваше имя:",
        "enter_age": "Введите ваш возраст (только цифры):",
        "enter_gender": "Выберите ваш пол:",
        "male": "Мужчина 👨",
        "female": "Женщина 👩",
        "enter_height": "Введите ваш рост (см):",
        "enter_weight": "Введите ваш вес (кг):",
        "enter_goal": "Выберите вашу цель:",
        "goal_weight_loss": "Похудение 📉",
        "goal_mass_gain": "Набор массы 💪",
        "goal_health": "Здоровье ❤️",
        "allergy_question": "У вас есть аллергия на какие-либо продукты?",
        "yes": "Да",
        "no": "Нет",
        "enter_allergy": "На какие продукты у вас аллергия? Напишите:",
        "calculating": "⏳ Анализ ваших данных...",
        "onboarding_complete": "✅ Поздравляем! Вы успешно зарегистрировались.",
        
        # Main Menu
        "menu_plan": "📅 Мой план",
        "menu_profile": "👤 Профиль",
        "menu_premium": "💎 Премиум",
        "menu_progress": "📈 Мой прогресс",
        "menu_feedback": "✍️ Отзыв",
        "menu_settings": "⚙️ Настройки",
        
        # Profile
        "profile_title": "👤 **Ваш Профиль**",
        "name": "Имя",
        "age": "Возраст",
        "gender": "Пол",
        "height": "Рост",
        "weight": "Вес",
        "goal": "Цель",
        "allergies": "Аллергия",
        "status": "Статус",
        "premium": "Премиум",
        "free": "Бесплатный",
        "edit_profile": "✏️ Редактировать",
        "back": "Назад",
        
        # Premium
        "premium_title": "💎 **Премиум Подписка**",
        "premium_desc": "С Премиум подпиской вы получаете:\n\n✅ Индивидуальный AI план тренировок\n✅ Индивидуальный AI план питания\n✅ Безлимитные запросы\n✅ Быстрая поддержка",
        "buy_1_month": "1 месяц - 50,000 сум",
        "buy_3_months": "3 месяца - 120,000 сум",
        "payment_success": "Оплата прошла успешно! Вам выдана Премиум подписка.",
        
        # Workout
        "btn_workout": "🏋️‍♂️ План тренировок",
        "btn_meal": "🍏 План питания",
        "choose_plan_type": "Какой план вам нужен?",
        "generating_plan": "⏳ AI составляет план...",
        
        # Errors
        "error_generic": "❌ Произошла ошибка.",
        "error_number": "❌ Пожалуйста, введите число.",
        "enter_phone": "Отправьте ваш номер телефона:",
        "invalid_phone_format": "❌ Пожалуйста, отправьте ваш номер телефона как контакт 👇\n\nНажмите кнопку ниже:",
        "name_cannot_be_empty": "❌ Имя не может быть пустым.",
        "enter_age_error": "Пожалуйста, введите возраст цифрами:",
        "enter_age_range_error": "Введите правильный возраст (10-120):",
        "old_button": "Старая кнопка.",
        "enter_height_error": "Пожалуйста, введите рост цифрами (см):",
        "enter_height_range_error": "Введите правильный рост (50-250 см):",
        "enter_weight_error": "Введите правильный вес (20-300 кг):",
        "choose_activity": "Выберите уровень физической активности:",
        "choose_goal": "Выберите вашу цель:",
        "allergy_details_prompt": "📝 На какие продукты у вас аллергия или какие есть заболевания?\n\nНапример: орехи, молоко, яйца, глютен, морепродукты",
        
        # Activity Levels
        "activity_sedentary": "Малоподвижный 🪑",
        "activity_light": "Слегка активный 🚶‍♂️",
        "activity_moderate": "Умеренно активный 🏃‍♂️",
        "activity_active": "Очень активный 🏋️‍♂️",
        "activity_athlete": "Атлет 🔥",
        
        # Main Menu Buttons
        "btn_calorie": "🍽 Анализ калорий",
        "btn_habits": "🔁 Привычки",
        "btn_trainer": "🎯 Личный тренер",
        "btn_challenges": "🔥 Челленджи",
        "btn_premium": "💎 Премиум",
        "btn_profile": "👤 Профиль",
        "btn_referral": "🔗 Реферал",
        "btn_feedback": "📩 Обратная связь",
        
        # Other Buttons
        "btn_ai_workout": "🤖 AI план тренировок",
        "btn_ai_meal": "🥦 AI план питания",
        "btn_calorie_premium": "🍽 Анализ калорий (премиум)",
        "btn_water": "💧 Пить воду",
        "btn_sleep": "😴 Сон",
        "btn_mood": "🙂 Настроение",
        "btn_steps": "🚶 Шаги",
        "btn_habit_stats": "📊 Статистика привычек",
        "btn_ai_qa": "❓ AI вопрос-ответ",
        "btn_ai_recipe": "🍳 AI рецепт",
        "btn_ai_shopping": "🛒 AI список покупок",
        "btn_points": "📊 Мои баллы",
        "btn_rewards": "🎁 Награды",
        "btn_rules": "📜 Правила",
        "btn_back_premium": "⬅️ Премиум меню",
        "btn_weekly_challenge": "📆 Недельный челлендж",
        "btn_monthly_challenge": "🗓 Месячный челлендж",
        "btn_friends_challenge": "👥 Челлендж с друзьями",
        "btn_leaderboard": "🏆 Таблица лидеров",
        "btn_edit_profile": "✏️ Редактировать данные",
        "btn_health_stats": "📊 Статистика здоровья",
        "btn_change_goal": "🎯 Изменить цель",
        "btn_buy_premium": "💳 Купить Премиум",
        "btn_tariffs": "ℹ️ Тарифы",
        "btn_coins": "🟡 Yasha Coin",
        "btn_workout_done": "Тренировка выполнена ✅",
        "btn_water_done": "Воду выпил 💧",
        "btn_phone_request": "📱 Отправить номер телефона",
    },
    "en": {
        "select_language": "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык / 🇬🇧 Select language",
        "language_selected": "✅ English language selected.",
        "welcome": "Hello, {name}! Welcome to YASHA Fitness Bot.",
        "enter_name": "Enter your name:",
        "enter_age": "Enter your age (numbers only):",
        "enter_gender": "Select your gender:",
        "male": "Male 👨",
        "female": "Female 👩",
        "enter_height": "Enter your height (cm):",
        "enter_weight": "Enter your weight (kg):",
        "enter_goal": "Select your goal:",
        "goal_weight_loss": "Weight Loss 📉",
        "goal_mass_gain": "Muscle Gain 💪",
        "goal_health": "Health ❤️",
        "allergy_question": "Do you have any food allergies?",
        "yes": "Yes",
        "no": "No",
        "enter_allergy": "What are you allergic to? Please type:",
        "calculating": "⏳ Analyzing your data...",
        "onboarding_complete": "✅ Congratulations! You have successfully registered.",
        
        # Main Menu
        "menu_plan": "📅 My Plan",
        "menu_profile": "👤 Profile",
        "menu_premium": "💎 Premium",
        "menu_progress": "📈 My Progress",
        "menu_feedback": "✍️ Feedback",
        "menu_settings": "⚙️ Settings",
        
        # Profile
        "profile_title": "👤 **Your Profile**",
        "name": "Name",
        "age": "Age",
        "gender": "Gender",
        "height": "Height",
        "weight": "Weight",
        "goal": "Goal",
        "allergies": "Allergies",
        "status": "Status",
        "premium": "Premium",
        "free": "Free",
        "edit_profile": "✏️ Edit",
        "back": "Back",
        
        # Premium
        "premium_title": "💎 **Premium Subscription**",
        "premium_desc": "With Premium subscription you get:\n\n✅ Individual AI workout plan\n✅ Individual AI meal plan\n✅ Unlimited requests\n✅ Fast support",
        "buy_1_month": "1 month - 50,000 UZS",
        "buy_3_months": "3 months - 120,000 UZS",
        "payment_success": "Payment successful! You have been granted Premium subscription.",
        
        # Workout
        "btn_workout": "🏋️‍♂️ Workout Plan",
        "btn_meal": "🍏 Meal Plan",
        "choose_plan_type": "Which plan do you need?",
        "generating_plan": "⏳ AI is generating plan...",
        
        # Errors
        "error_generic": "❌ An error occurred.",
        "error_number": "❌ Please enter a number.",
        "enter_phone": "Please send your phone number:",
        "invalid_phone_format": "❌ Please send your phone number as a contact 👇\n\nPress the button below:",
        "name_cannot_be_empty": "❌ Name cannot be empty.",
        "enter_age_error": "Please enter your age in numbers:",
        "enter_age_range_error": "Please enter a valid age (10-120):",
        "old_button": "Old button.",
        "enter_height_error": "Please enter your height in numbers (cm):",
        "enter_height_range_error": "Please enter a valid height (50-250 cm):",
        "enter_weight_error": "Please enter a valid weight (20-300 kg):",
        "choose_activity": "Select your physical activity level:",
        "choose_goal": "Select your goal:",
        "allergy_details_prompt": "📝 What allergies or medical conditions do you have?\n\nExample: nuts, milk, eggs, gluten, seafood",
        
        # Activity Levels
        "activity_sedentary": "Sedentary 🪑",
        "activity_light": "Lightly Active 🚶‍♂️",
        "activity_moderate": "Moderately Active 🏃‍♂️",
        "activity_active": "Very Active 🏋️‍♂️",
        "activity_athlete": "Athlete 🔥",
        
        # Main Menu Buttons
        "btn_calorie": "🍽 Calorie Analysis",
        "btn_habits": "🔁 Habits",
        "btn_trainer": "🎯 Personal Trainer",
        "btn_challenges": "🔥 Challenges",
        "btn_premium": "💎 Premium",
        "btn_profile": "👤 Profile",
        "btn_referral": "🔗 Referral",
        "btn_feedback": "📩 Feedback",
        
        # Other Buttons
        "btn_ai_workout": "🤖 AI Workout Plan",
        "btn_ai_meal": "🥦 AI Meal Plan",
        "btn_calorie_premium": "🍽 Calorie Analysis (Premium)",
        "btn_water": "💧 Drink Water",
        "btn_sleep": "😴 Sleep",
        "btn_mood": "🙂 Mood",
        "btn_steps": "🚶 Steps",
        "btn_habit_stats": "📊 Habit Stats",
        "btn_ai_qa": "❓ AI Q&A",
        "btn_ai_recipe": "🍳 AI Recipe",
        "btn_ai_shopping": "🛒 AI Shopping List",
        "btn_points": "📊 My Points",
        "btn_rewards": "🎁 Rewards",
        "btn_rules": "📜 Rules",
        "btn_back_premium": "⬅️ Premium Menu",
        "btn_weekly_challenge": "📆 Weekly Challenge",
        "btn_monthly_challenge": "🗓 Monthly Challenge",
        "btn_friends_challenge": "👥 Friends Challenge",
        "btn_leaderboard": "🏆 Leaderboard",
        "btn_edit_profile": "✏️ Edit Profile",
        "btn_health_stats": "📊 Health Stats",
        "btn_change_goal": "🎯 Change Goal",
        "btn_buy_premium": "💳 Buy Premium",
        "btn_tariffs": "ℹ️ Tariffs",
        "btn_coins": "🟡 Yasha Coin",
        "btn_workout_done": "Workout Done ✅",
        "btn_water_done": "Drank Water 💧",
        "btn_phone_request": "📱 Send Phone Number",
    }
}

def get_text(key, lang="uz", **kwargs):
    """Get translated text by key and language code."""
    text = TRANS.get(lang, TRANS["uz"]).get(key, key)
    if kwargs:
        try:
            return text.format(**kwargs)
        except Exception:
            return text
    return text
